export default {
  id: "kanji",
  title: "Kanji 漢字",
  description: "Study set that includes cards to / from kanji characters, their on'yomi and kun'yomi readings, and meanings. Mnemonics for some of them are also  included as hints.",
  topic: "japanese",
  flashcards: {
    "RI1l+KhkjzALidLZpsxIc8QU4T4HCQ==": true,
    "FUZn2mO9nXuBlnonaW12m6ey3oWdpQ==": true,
    "9VrXesm1JWVJRQwc8v+hlSKzdhc2YQ==": true,
    "x3z+FOfkhzNPcf0xXEJRE6H52R1SZA==": true,
    "h9got83aJoNu8lP1LxCBxllRj/GA6Q==": true,
    "tx/kwtNVqHCZ2Pcthk4GP4XJE1i3rg==": true,
    "4H3YRWuQZAUx3OHg2H+TZD4xjcng+A==": true,
    "AhWk48S4jgEWVTgK9NjVryhIFzTvuQ==": true,
    "V84fd78G/roC1ZaGu0MfAAiWNr9siQ==": true,
    "ZeAa+o5CZI9/6TP50Rk0Xgj0A7l2jA==": true,
  },
  data: [
    { id: "D65sVM32EZZP5PjMQ22v69tWM6jbtg==", K: "一", M: "One", OY: "! いち, いつ", KY: "ひと", MM: "" },
    { id: "iHIMwgCDEtQY0olq5P5eSsSjZvEHxA==", K: "去", M: "Past", OY: "! きょ, こ", KY: "さ", MM: "When your past is dirty, it stinks (KOKUYOR - こ, きょ)" },
    { id: "rxtKUWidFVH9irX/9YjZVUTtvVFYdA==", K: "号", M: "Number", OY: "! ごう", KY: "-", MM: "This kanji consists of two numbers, 0 and 5 on top of each other. That's why reading starts with (ご): ごう. It's not just ご because then it would mean 5." },
    { id: "rBgfrYlcrx2ME2PAlM/lO/ReNhnrgA==", K: "央", M: "Center", OY: "! おう", KY: "-", MM: "Looks like middle (中) kanji. In the center, there is always the king (おう), thus the reading." },
    { id: "p83JR6NDiK85n5RmICZy1egSh7oiEA==", K: "打", M: "Hit", OY: "! だ", KY: "う, ぶ", MM: "Left part is fingers radical, right part looks like child radical. Think of this as HITting a child, a typical case of dayak (だ)" },
    { id: "Imfcp7dT5Yg71uvb+SHdhMZQgurN0Q==", K: "氷", M: "Ice", OY: "ひょう", KY: "! こおり", MM: "In the core (こお) of ice, there is a ring (り). Marriage proposals are getting creative." },
    { id: "QgqXjj5FZZ4CQh2tay5hmt+bMcELFQ==", K: "申", M: "Say Humbly", OY: "しん", KY: "! もう",  MM: "This consists of a cross and a mouth. Something like controlling your mouth to speak humbly instead of sounding like an asshole. As for the reading, remember from the involvement of the mouth (もう) radical. This kanji is also used for saying 'hello' on the phone: '申し申し' so remember もう from there." },
    { id: "f2yzBOhp50oyMkWNAPdmJUmGQj6T3w==", K: "先", M: "Previous, Ahead, Past, Former", OY: "! せん", KY: "さき, まず", MM: "There's a 'pi' in this kanji, (pi)revious. Geçen (SE)fer / Geçen (SEN)e -> せん. Remember from your mom telling you a story about the past: (sen - せん)eler evvel (sen - せん) doğmadan önce, ..." },
    { id: "UAh26ZSJYxtN1gQJVGAU+AbaSA7qZg==", K: "名", M: "Name, Famous", OY: "! めい, みょう", KY: "な", MM: "My (めい) name is..." },
    { id: "M/7YX7kZB1Yj1QuZxvAhC6LLyL1i4g==", K: "年", M: "Year", OY: "! ねん", KY: "とし", MM: "NinEteeN - ねん" },
    { id: "5V9AEFSKKNrzaUSLhACxCQO0ZuBBpg==", K: "早", M: "Early, Fast, Quick", OY: "! そう", KY: "はや, さ", MM: "When your alarm goes off, it's soo (そう) damn EARLY. To make it on time, you gotta be FAST and QUICK." },
    { id: "HReVs4EZqHElrf58JLSB6Y6xqUUsug==", K: "百", M: "Hundred", OY: "! ひゃく", KY: "もも", MM: "Hundred sun-leaf eating ducks would go ひゃく!" },
    { id: "uWyeHuzyEF/3blwCJF2RVwPpQdgsPw==", K: "男", M: "Man", OY: "! だん, なん", KY: "おとこ", MM: "Remember Danna's (だん, なん) from Memoirs of a Geisha" },
    { id: "lOLpYBgUEAQT1Cln9clDVEDI9OOD1Q==", K: "世", M: "World, Generation", OY: "! せ, せい", KY: "よ", MM: "" },
    { id: "BtjNR/RqTZnJTfJaveMgPBNHp0Isbg==", K: "他", M: "Other", OY: "! た", KY: "ほか", MM: "You can't pick an alligator leader, you have to pick anOTHER animal. You need to be able to TAme (た) it." },
    { id: "ARv4Yy+9qh8KlO4r0S3zJrT7S7Yarg==", K: "代", M: "Substitute, Replace, Period, Age", OY: "! だい", KY: "か, かわ, しろ", MM: "The leader can't come to the ceremony, you have to find a SUBSTITUDE to REPLACE. Becuase of his old AGE, he forgot the time PERIOD of the ceremony. His age is so old, he is about to DIE (だい)" },
    { id: "a+CpbcOKYeSUdMKjJe80R+Fr/GBRZA==", K: "皿", M: "Plate", OY: "-", KY: "! さら", MM: "Sarah is washing the dishes." },
    { id: "8kyXlmj2FLPLR9t6W9EyHa5ozC33xw==", K: "休", M: "Rest", OY: "! きゅう", KY: "やす", MM: "The leader is RESTing by the CUCUMBER (きゅう) tree." },
    { id: "HqRXq+tQh/tzktm2xrpD7ijn7+XObA==", K: "字", M: "Letter, Character, Symbol", OY: "! じ", KY: "-", MM: "This kanji is in the word student (学生). What things do students learn at school? LETTERs and some JImnastics (じ)." },
    { id: "UdU5/jt42NTEgdsjkj7LG0LYkE11/g==", K: "気", M: "Energy", OY: "! き, け", KY: "いき", MM: "元気 - Genki" },
    { id: "jjQ6LNzcbBZKdebw4MC8pfsaIodrNw==", K: "竹", M: "Bamboo", OY: "-", KY: "! たけ", MM: "There's a leaf hanging down the bamboo tree, you reach for it and TAKE (たけ) it." },
    { id: "uIh5IDIm5qqhIjtrpL371/q/fnRugw==", K: "糸", M: "Thread", OY: "し", KY: "! いと", MM: "What's a thread without a process id? An incognITO (いと) thread." },
    { id: "gqQ1osjkebSqKUg4AwRlJXP0b4HR0Q==", K: "耳", M: "Ear", OY: "じ", KY: "! みみ", MM: "" },
    { id: "v1Ts2AFCvUjHsoxhPkePHyeTgdrq1g==", K: "主", M: "Master, Main", OY: "! しゅ", KY: "おも, ぬし", MM: "Master will shoot you (しゅ)" },
    { id: "l7mnt9+4bIw1DvK71RG/MjxbebKTqw==", K: "平", M: "Flat, Peace", OY: "! へい, ひょう, びょう", KY: "たいら, ひら", MM: "Room - へや, When you enter a FLAT, you say hei (へい) to the people there and make the PEACE sign." },
    { id: "6Nc7KubXAxrrqMAa33FOlJyxWCEX2A==", K: "礼", M: "Thanks", OY: "! れい", KY: "-", MM: "When given an umbrella in the sun to protect from sun RAYS (れい), a good spirited person might say THANKS." },
    { id: "TXl9o+iBHnshMhQNW7ARW25sUK3J3w==", K: "虫", M: "Insect", OY: "ちゅう, き", KY: "! むし", MM: "むしのおんな" },
    { id: "sn2kRy51X+nuyQWIq9xTowDII6V1EA==", K: "村", M: "Village", OY: "そん", KY: "! むら", MM: "Measurement of trees, to build a village. Klasik köylü ismi: Murat (むら)" },
    { id: "T3vETer+DfGgjZOfobz2LygOflBEQA==", K: "町", M: "Town", OY: "! ちょう", KY: "まち", MM: "When you go to another town, you say 'chiaou!' (ちょう) to your friends." },
    { id: "xUqXxFp8sUGsf96ArYb76in02DXS0w==", K: "花", M: "Flower", OY: "か, け", KY: "! はな", MM: "Hannah (はな) Montana always had flowers in her head." },
    { id: "EIPognPVi8Z3EyYT3x1Ixl3efEB84g==", K: "見", M: "See", OY: "けん", KY: "! み", MM: "Ear is みみ" },
    { id: "vFkxyAdnLmUz25/DPFJN969LJYa6Tg==", K: "貝", M: "Shellfish", OY: "-", KY: "! かい", MM: "It's hard to hold a shellfish because they are slippery (kaygan - かい)" },
    { id: "Ai7x1EVP6zecZSGVClbIrG5oH2z5uA==", K: "赤", M: "Red", OY: "せき", KY: "! あか", MM: "" },
    { id: "IYvkfuN57oEuCeudW/KRlC+buu81hA==", K: "足", M: "Foot, Leg, Sufficient", OY: "! そく", KY: "あし, た", MM: "What do you wear on your foot? Sock (そく)" },
    { id: "W3qPXSZ/qEzbhH1mAvXlOlj2HBAPsg==", K: "車", M: "Car", OY: "しゃ", KY: "くるま", MM: "What do cars have? Şanzıman (しゃ)" },
    { id: "dpQdyGz4vzFjcVox+8lPeGICGN2kog==", K: "不", M: "Not", OY: "! ふ", KY: "-", MM: "If a person is NOT smart, they are a fool (ふ)" },
    { id: "IozUfklqNBxWSmhxouIQPB5utk1ZfQ==", K: "仕", M: "Doing, Do", OY: "", KY: "", MM: "Leader DOING samurai, because the samurai happens to be a she (し)." },
    { id: "7X0yJ1IFtm261f/cA+3dFfD+1c0IRA==", K: "宝", M: "Treasure", OY: "! ほう", KY: "たから", MM: "Ball under a roof is a treasure, because usually kids are not allowed to play with the ball at HOME (ほう)." },
    { id: "GP/kXtR/d3xvxiWkVZzDvSh+g7S60g==", K: "石", M: "Stone", OY: "! せき", KY: "いし", MM: "Taş (STONE - argoda: sexy - せき)" },
    { id: "Nuew7ZZt89joXHaSFQRbTSWhJ+uaKA==", K: "写", M: "Copy", OY: "! しゃ", KY: "うつ", MM: "Looks like numbers. What do you do with numbers? you COPY them to your phone. But if you COPY the answers in an exam - SHAME (しゃ) on you." },
    { id: "", K: "", M: "", OY: "", KY: "", MM: "" }
  ]
}
