export default {
  id: "radicals",
  title: "Radicals 部首",
  description: "Study set that includes cards to / from radicals.",
  topic: "japanese",
  flashcards: {
    "+xuV0JqxtKCxeVJMQT4f/w4vCbO/5Q==": true,
    "KWM2Kt8EjnwN3jeJGdWfQ/iIIhvBBQ==": true,
  },
  data: [
    { id: "KJagVNu0eody3mXunaHoYxp7HAq7Bw==", M: "一", R: "Ground" },
    { id: "uBSBtUzD5T7PhnZ4mhcY3gjbOFTumQ==", M: "ハ", R: "Fins" },
    { id: "sY2e8fNj4jTQBp3DirZF9M1yz02ZUA==", M: "丶", R: "Drop" },
    { id: "yr/4XOZSUjy8b1F/Li42N8GjkqLGdw==", M: "丿", R: "Slide" },
    { id: "RsgXF+3BEa0SyV91wdymzfXx5jsvZA==", M: "亅", R: "Barb" },
    { id: "YUTxeGzZaxmtqZZfRnkuQuRWteccCw==", M: "二", R: "Two" },
    { id: "y5xb097xRRaXXC3V85ZZ8zTnTLEVfQ==", M: "亠", R: "Lid" },
    { id: "kFyiqlDT57P8f9Jx72zezphX478xLw==", M: "大", R: "Big" },
    { id: "SIttVI3Y3zJED9U5NtfAtYtH/gmI3A==", M: "人", R: "Person" },
    { id: "A2iX/xv0vfB9BfVqteoO+RJTNcQgUg==", M: "入", R: "Enter" },
    { id: "18In2UXlJNaN6gGsmYp/omedU3/mUQ==", M: "力", R: "Power" },
    { id: "4PoBD/FZTWidKlnlXsMHygLPj+NF1Q==", M: "勹", R: "Prison" },
    { id: "KvWREWlCOhyzSQeFxF60i4xrv6Rzqg==", M: "口", R: "Mouth" },
    { id: "E2tnGiYD+/H2SYDoJ9QwJCrhFIbgdQ==", M: "女", R: "Woman" },
    { id: "0dbTWvU1RLTiP8qdqzQLHNz/+CG0Rw==", M: "七", R: "Seven" },
    { id: "CJ84mnIAM39IsdiKX14fOLHWdXJhdw==", M: "十", R: "Cross" },
    { id: "pXjmCPpVUkzO6xcYPHy6UD1pzLoC6w==", M: "山", R: "Mountain" },
    { id: "oUvEusRqh2aVybHr/FfFUG4uDdHlxQ==", M: "川", R: "River" },
    { id: "pnsLIuZ73GXqDGq8SO+XvM9MlbSWxQ==", M: "木", R: "Tree" },
    { id: "7o2r6mSRvypkcLHW8OGt0T1qmgOYeQ==", M: "工", R: "Construction" },
    { id: "bNzL7I6tHDmwXos7gTm6bUkAQLZBNA==", M: "九", R: "Nine" },
    { id: "xJQWsH1L1nBY1mqvtKfrO8aUhv4x2Q==", M: "丆", R: "Leaf" },
    { id: "0ZGXiIkHiwuuQFfXwL7PqbIFbfYaYQ==", M: "𠂉", R: "Gun" },
    { id: "Yhi5Kz2bdaMYlAn7c0ui0PB30yXZvA==", M: "日", R: "Sun" },
    { id: "xxyOJvSmobOV0GcNHYUlD5KriqCuHw==", M: "ト", R: "Toe" },
    { id: "A3RiId4JnHypwIQ7PdUrCvo5ekNNlg==", M: "丨", R: "Stick" },
    { id: "WaLXeUMUcyjYgHEoBSGdm6GWBEM97w==", M: "土", R: "Dirt" },
    { id: "dD8A2DUTtiYSdS2F2rc/pEw+DDYCPg==", M: "刀", R: "Sword" },
    { id: "YPymFWyaQYTfTdh4DrIkWAdsVY8zvw==", M: "ナ", R: "Narwhal" },
    { id: "p/NDY2O2kElVxUgEoH/+kgpg4JQrOQ==", M: "丁", R: "Street" },
    { id: "+o+TIDSXfim08C2XiX2YuMw96LR+/g==", M: "儿", R: "Legs" },
    { id: "W7wE/CCn1orVBCiIkjqoaKTmDbTtfw==", M: "冂", R: "Head" },
    { id: "XHOiMufW1ZioVazklqwRsbe6FxysfA==", M: "又", R: "Stool" },
    { id: "oXhT/tDkSDfX55PsJ97XqcsGj5V2dA==", M: "メ", R: "Treasure" },
    { id: "RqljUUq1YKqenbljcQl4zmuaEDoO3w==", M: "千", R: "Thousand" },
    { id: "9vVKk6oFt12SN4iCKTRWxemN0EMrvg==", M: "夕", R: "Evening" },
    { id: "hzmgZCKVAfXbP1aEyyl7f+w/vcJOHQ==", M: "子", R: "Child" },
    { id: "JU8PBxwwqDiq29J8jcGNOBOs+AByzA==", M: "小", R: "Small" },
    { id: "WmyUramLiHiRb9LDRrqEvPeu0TOkFg==", M: "弓", R: "Bow" },
    { id: "mSyaZACW2QRRXTf5lJBcn4Mv8ULrkQ==", M: "尸", R: "Flag" },
    { id: "Zg5Wkp05WSsteVuPYKRNpwVdqYmB4A==", M: "彡", R: "Hair" },
    { id: "khYZCM7ujdV/UQzeu9DLNUlLRkyBhQ==", M: "五", R: "Five" },
    { id: "0vOCvfBK0rFn6UFH6CvZR+IFW0FyNA==", M: "天", R: "Heaven" },
    { id: "hDKkVS6INiNgEuMTq5vJK2/KdTI9eQ==", M: "手", R: "Hand" },
    { id: "E0fBBXYow4U06sxsM3X8VBBY5KD9jA==", M: "文", R: "Writing" },
    { id: "g8QXJzXbSIlVSEfdQtMspTtn7pNKNQ==", M: "月", R: "Moon" },
    { id: "6LWwDqWiKz7vpxCmd/Za33K4kbkQaw==", M: "止", R: "Stop" },
    { id: "HxiMqxfbn7vruVpaJBxGPnNDsVT00w==", M: "水", R: "Water" },
    { id: "HxiMqxfbn7vruVpaJBxGPnNDsVT00w==", M: "火", R: "Fire" },
    { id: "u9oiWpSLjdPI8K8xcbgo20Pl7ZDDMg==", M: "犬", R: "Dog" },
    { id: "xNmK6NvCt+fOauVGnGSQ+BQFXMPlRQ==", M: "王", R: "King" },
    { id: "IHYVM/i13lnAXQCNXGBqg72ojPQ2EA==", M: "中", R: "Middle" },
    { id: "bKBqhoHZo9dGlrkY7xKss8KY+vC65A==", M: "本", R: "Book" },
    { id: "92mMdk12szlUN8GhT1zL3wNSQQ7c1A==", M: "田", R: "Rice Paddy" },
    { id: "K8PEcQ/ro0SRrcWoenVEkOzjgklHFw==", M: "白", R: "White" },
    { id: "qsHm2KrZ/gYqDKpHIa14gNRnCBV5nA==", M: "目", R: "Eye" },
    { id: "lfQmyY78YqzBQyMxsE41mq2UfCaVgQ==", M: "石", R: "Stone" },
    { id: "zIYVF034es2542NQ0CTPDImT+HbeMw==", M: "立", R: "Stand" },
    { id: "/gK+dt57eZ+1/ZZhR24wtZI2izBnGg==", M: "牛", R: "Cow" },
    { id: "xX4j/RaIJmuQUX30/7He/5ZR8b+8Yw==", M: "ム", R: "Private" },
    { id: "ReYlIQo3NCgemcrkCSn+OK3JhJIizw==", M: "匕", R: "Spoon" },
    { id: "InG9m834qZywDoMsHvehoiwe7hkG5A==", M: "夂", R: "Winter", MM: "It looks like the things you put on your shoes to walk on snow." },
    { id: "3atRQ+/yijbWAtbEtF65VZacCIqdbA==", M: "干", R: "Dry" },
    { id: "xoCZRiyRjvTXRN/sbZrdT0SvIZYmUg==", M: "广", R: "Canopy" },
    { id: "rEppyqDBz/ndb/ikmPGq7VlhwYleaA==", M: "扌", R: "Fingers" },
    { id: "CKM7QIIUrotgO+Xo3cRGwfLiWNQfFg==", M: "元", R: "Origin" },
    { id: "V2x+Pz4BAqTQiCr81RGAbh8GZR+paw==", M: "心", R: "Heart" },
    { id: "ABATXDf6sgkWLXbY524NMLn6X538AQ==", M: "方", R: "Direction" },
    { id: "JmhsOMomiK+GeWVsTLwURXRSexBx/A==", M: "毛", R: "Fur" },
    { id: "PkGoXrglhjgMx7f4L9DXzoq/1mq3+A==", M: "父", R: "Father" },
    { id: "yKG2Idu/K7kBO2oKtK5HrbMXBD2O2A==", M: "古", R: "Old" },
    { id: "jum5TXEbjmR1LW/ki6TBPQotbHLk7g==", M: "用", R: "Task" },
    { id: "4fyE734WDc+i02Aq4IKGetE4OABUDA==", M: "矢", R: "Arrow" },
    { id: "3V5Wb4eXnI2e9yrn+AlqOSfxoLcZOg==", M: "戸", R: "Door" },
    { id: "wOy9Ig8+oKEpygn8ZA/oBv0Ef2e6dQ==", M: "幺", R: "Poop" },
    { id: "bfOUU4QQVbn+INW9oLB8uVFTFFE1RA==", M: "巾", R: "Towel" },
    { id: "1lIfAm2fyfcERTqPRRDaMC0oMxwiLQ==", M: "生", R: "Life" },
    { id: "jHvm7tRIW/pN1WfIAPwIKLsl9C3GAA==", M: "今", R: "Now" },
    { id: "yEAs9qmDLpleAgur5JBg8xsaMTbXKg==", M: "𠆢", R: "Hat" },
    { id: "koo9x0KANsm3RyB7k6ZmWGd7kU2Jvg==", M: "⺌", R: "Triceratops" },
    { id: "FDnFzZamUvd8lPpoig3WhayzlSGrBQ==", R: "寸", M: "Measurement" },
    { id: "6UX2aUUENH1eq/0t02p+zrwbTiCYXA==", R: "ｲ", M: "Leader" },
    { id: "W5SbK85K1Nqkk5HyKGN31YfrFq0J6A==", R: "冖", M: "Forehead" },
    { id: "fCqFBrBoM5LBoFB9sJVDw6V3SEcVRA==", R: "也", M: "Alligator" },
    { id: "rfwJbaa89v8qsQmwmPc9nTYZPCkrOw==", R: "宀", M: "Roof" },
    { id: "d4K1iKSSYzwoIf/IhpRaZimoKklR/A==", R: "弋", M: "Ceremony", MM: "This looks like a person with a long dress running behind them, just like the bride in a wedding ceremony." },
    { id: "BfhAKwmy/B0q+jtaRC9MfuCcBlTAIw==", R: "ネ", M: "Spirit", MM: "Looks like a ghost trying to scare people off." },
    { id: "UrU4AwV4njv/Dq3oIBSmY/6KNUNLDQ==", R: "支", M: "Branch", MM: "A cross is branching off of a stool" },
    { id: "zYf1bs+OaC2uiTaTaIgzsPwT4MArgw==", R: "气", M: "Energy" },
    { id: "SuXZU1MBxep0jfObcr/rubTv4v7h4Q==", R: "世", M: "World" },
    { id: "bwu4Cp88GE1Mao1yY9axB2yS4eDWVQ==", R: "皿", M: "Plate", MM: "Looks like plates drying on a rack" },
    { id: "ngJVsy82psfdW5hBu4gJg3E2GMwwaw==", R: "竹", M: "Bamboo", MM: "Looks like a bamboo tree" },
    { id: "TJlttYoN39iGqqiSIFuP0VpZhhGUCg==", R: "糸", M: "Thread", MM: "Looks messy, just like a thread (ie. computer science)" },
    { id: "e+teAc4IAxcpdNweKAE6muPJZUUVlw==", R: "耳", M: "Ear", MM: "This looks like eye (目). If you go blind, your ear become your new sense of sight. Thus, it's a modified version of eye." },
    { id: "8ou9+rDHixcGFL0RI6k8s95nQ4vCyQ==", R: "虫", M: "Insect", MM: "Looks like a snail" },
    { id: "bqhDaOmrC0WJfi37qQOfZPyeeblyHg==", R: "艹", M: "Flowers", MM: "What sticks from the ground like in this radical? Flowers." },
    { id: "Yrb+upYOasiWkiQthYGVQsW01wqItw==", R: "見", M: "See", MM: "This is literally eye (目) that has legs (儿)" },
    { id: "D/9iiPqprMMHygMkQPw+8dhRMCbA0A==", R: "赤", M: "Red", MM: "This looks like that guy from X-men that shoots lasers from the eye. What color is that laser? Red." },
    { id: "2xrWbqmuUu9OgLvNNet8QGVZeGbT5A==", R: "車", M: "Car", MM: "Looks like a top-down view of a car" },
    { id: "jskBvZG+VgSPq2TkXmII42bgBVYKRw==", R: "貝", M: "Shellfish", MM: "ie. Midye. The legs are the shell, the middle part is eye of the clam." },
    { id: "IpzPREchpsZe6HUl/X+QO6nbcyi82Q==", R: "足", M: "Foot", MM: "Dude doing a dragon kick on his foot" },
    { id: "fKMJT5rzQg+kxIaudSpEA7zs5Dz+Fw==", R: "不", M: "Not", MM: "Looks like a dude turning his back - as a 'nope - not' gesture" },
    { id: "tbwmBa/vy7SAVbvTVqQXiqRTQiPikQ==", R: "士", M: "Samurai", MM: "Like dirt, but arms are longer. Because it's holding a sword." },
    { id: "EDOUO85CTgmtjDJc/8B39ZjhpYCGcQ==", R: "米", M: "Rice" },
    { id: "P1ZOBgxHFchRZ+X0Jhpbc0WcyHbzLg==", R: "彳", M: "Loiter", MM: "The leader (ｲ) radical has a little thing at the top, causing him to loiter." },
    { id: "RXRH9Qb4nHDSPQ5umdrd6pLKPz8t0g==", R: "巴", M: "Bed" },
    { id: "yNU8rr6sDuEGemRjfo/LbLG8SkfTJg==", R: "兀", M: "Pi" },
    { id: "w2cgimT5ubYimDt6XVQFbobU2G93ng==", R: "厂", M: "Cliff" },
    { id: "udryCo6YVTST8dqX4heDBk8MajpZRA==", R: "主", M: "Master" },
    { id: "GmEvPXVURvzBCTAxxuY14kdo/DdZMg==", R: "乚", M: "Umbrella", MM: "Upside down umbrella" },
    { id: "0GUd6gSABjYNixtKvoMOnpgt1jKbRg==", R: "乞", M: "Beggar", MM: "Looks like a man extending his arm to ask for spare change." },
    { id: "+7BjVPMNTLcqb2KWS3m8mEJSKRZmFw==", R: "丷", M: "Horns" },
    { id: "DDRhW7/TKAmTxZTuAzCV+vbkaM5jQw==", R: "业", M: "Spikes" },
    { id: "lvpV1J0hXMSyIaZtUZzUskrF1wlGCQ==", R: "氵", M: "Tsunami", MM: "When there are too many drops, there you have a tsunami" },
    { id: "zPIkp5uM9PGlskQTYfOK8Xn/upCXrA==", R: "耂", M: "Coffin" },
    { id: "1CP9Pyd7NbWtw4/10UPs1fwL+nCo0w==", R: "ヨ", M: "Wolverine" },
    { id: "mB1uxJAUCxSBTCMUnaNYq5LXQ/7stA==", R: "廾", M: "Twenty", MM: "You have 十 plus 十, twenty" },
    { id: "0RJ6ye/EcGoh0piT06XD8WYqUMuAxQ==", R: "毋", M: "Window" },
    { id: "UyObmsF0W/uBoWwwoSaP8UCLgKLsXg==", R: "肉", M: "Meat" },
    { id: "rw/ukW/rvuTh4w9ZAfz8naWrhY010A==", R: "自", M: "Self" },
    { id: "bKpll1e5+gLB9Jeh4F14YqiyuKPR8A==", R: "色", M: "Color", MM: "The middle part looks like 3D glasses, which has two two COLOR lenses." },
    { id: "ZFwXD5julqTNLryP8OhN+cgn1G+MRw==", R: "行", M: "Go", MM: "You have the radicals for loiter, two, and barb. Someone who uses two barbs on you while you're loitering really wants you to GO!! GO on, stop loitering outside of my convenience store, ya dang kids!" },
    { id: "uKcyThQ8cfrCbk1WsFrdnTBi2GaIkg==", R: "西", M: "West", MM: "A pi coming out of a mouth, the mouths of scientists from the WESTern world." },
    { id: "sSNdBB0r1HvzCwJMjjLX6MLadDDlZQ==", R: "可", M: "Lip Ring", MM: "Looks like mouth prison" },
    { id: "ml0mAnB77kRH7Y4qpgDQRoAI+Ni+TQ==", R: "斤", M: "Axe", MM: "Looks like an axe with a weird T attached to it" },
    { id: "ay2WvRjpUdPcCJlwhv+92awN59C3fw==", R: "言", M: "Say" },
    { id: "caBqlOLTC6U1efpI2aYzEm17P6bTzQ==", R: "金", M: "Gold", MM: "For some reason this reminds me of a bank (ie. as a building). What do banks deal with? Money / Gold." },
    { id: "/SK/Ood6cMfjzkfnqB7ZLlp+bMseRQ==", R: "雨", M: "Rain", MM: "Drops in the city - obviously rain." },
    { id: "90/nP0FWd1jaQzb1LZOYzcFu1tdT+w==", R: "青", M: "Blue", MM: "The upper part looks like the reflection of the moon on the lower side of the radical on the beautiful BLUE sea." },
    { id: "SEdIicSRXqQKe6KIZUc0trPzxhnKVQ==", R: "冋", M: "Mustache", MM: "The center part is the mouth. What's around the mouth ? The mustache." },
    { id: "UoGu+t84o1mKdMC6bZEC6L1hcP7KQQ==", R: "乍", M: "Key" },
    { id: "WLf2pFrCWqoub/Fo2loeD2mitwWz/g==", R: "冫", M: "Ice", MM: "Two drops of water is the next stage of water, which is ice." },
    { id: "wm+iqRt97Y5O1p5pKKDs3RxhEgPXzg==", R: "走", M: "Run", MM: "There's the foot at the bottom. " },
    { id: "k8YNCeA7k6031sD13/7ice3tkEQkEw==", R: "里", M: "Village", MM: "Some dirt around a rice paddy, perfect place to set up a village." },
    { id: "Hv8sTWyH8S0qyaJARhYJos4dXQxfdA==", R: "会", M: "Meet", MM: "Under the hat there are two people meeting in private." },
    { id: "Kx9vf1o8c8ZmgGHko2hCju10HzdGmQ==", R: "开", M: "Lantern" },
    { id: "ddbOgHKTnIA53DZiHlNrt561bSbHUw==", R: "羽", M: "Feathers", MM: "This radical looks like wings" },
    { id: "SWDOu1aUgj98LpZZnAigWuY/Bt+IXQ==", R: "L", M: "Lion" },
    { id: "u0Oxau0YVc2J7CRA5Krd43aSOCVOYA==", R: "凵", M: "Box" },
    { id: "SQz16ZsJ52HOi3aiqC357spth/oQxA==", R: "刂", M: "Knife" },
    { id: "vUls4T2WYEFWXLqLB8jXkhS+zOI3fw==", R: "斗", M: "Ladle" },
    { id: "gXppjCZil4Fh+xZO6pXks2try6t5Hg==", R: "ホ", M: "Angle" },
    { id: "3NYhoC/utVrd+Du7YrgtIL8JR32+6A==", R: "灬", M: "Boil" },
    { id: "pmsM7KyesJhxiSefa9MPZf0AFq3aWQ==", R: "歹", M: "Yakuza" },
    { id: "hxl6C38fWLDZixiJBK5WT5KfHm9ALg==", R: "未", M: "Jet" },
    { id: "W3rTBUw/nm0KFzk4hnLUXZAQMW3kYQ==", R: "禾", M: "Grain", MM: "There is the 'Thousand' kanji in this radical, because there are thousands of Grains of sand." },
    { id: "m318Rauh+xlVEYvy+rOxm8XE6zn8aw==", R: "羊", M: "Sheep" },
    { id: "caAEekbeziePRCegSD/LFgg2QoH2CQ==", R: "血", M: "Blood", MM: "What happens when you break a plate? The broken pieces cuts you and you bleed." },
    { id: "xPIVS+5ZXkSbnine2E+KJNJO/G+7+w==", R: "長", M: "This looks like a key having legs and walking. The key to walking LONG distances is to have legs" },
    { id: "qsUUFNYp7OCVEMYFQkpsiNMIX9ZZYg==", R: "食", M: "Eat" },
    { id: "T6FsgpDZkjsYUW1ILuW4iiPZBqvgbA==", R: "マ", M: "Mama" },
    { id: "a/mNGW4JifmwyZqraFZ311ipdQkXoA==", R: "欠", M: "Lack" },
    { id: "ypw8zJafSP/ggctgwGEmXTDl2Vlw1Q==", R: "占", M: "Fortune" },
    { id: "bts2bKji7hezWfK1iyx5Gi7SAAitUw==", R: "犭", M: "Animal" },
    { id: "wcsPy9hSyUZ6aQvziEldR7iCxUEXdA==", R: "首", M: "Neck" },
    { id: "e+kcf0VE02i8yjOND1OruWSGX49sPg==", R: "舌", M: "Tongue" },
    { id: "+FSwwCjvnzndnBIRCZzlqv9lpUKaeg==", R: "亡", M: "Death" },
    { id: "8S+pRUCg6pYjRdpQ3cG6vxc0APGBkw==", R: "市", M: "City" },
    // { id: "", R: "", M: "" },
  ]
}
