export default {
  id: "vocab",
  title: "Vocabulary 単語",
  description: "Study set that includes cards to / from vocabulary words.",
  topic: "japanese",
  flashcards: {
    "3UNJQV1ZhNMhiodJHR9RUzcJrIYKAg==": true,
    "JWaBtSN/LhH2FY9OtNEUGhtzlrbSkg==": true,
    "XgJBDHSMuPmtu3cIccMGTNLHQ+1YiQ==": true,
    "aHaaBZn7/QudfhNPOIh4HpWXpMsmqw==": true,
    "Rrh0lq/wRfXLXR2N6TvrFH8b2ZKCYA==": true,
    "ay0jJE81SFepPQHvlTavSmYTnP4MrQ==": true,
  },
  data: [
    { id: "UcMbHoTfSs/ZGHYCZUZXr2zSvK2SjQ==", V: "今", M: "Now", RR: "いま", MM: "'Imma' do it NOW!" },
    { id: "3572AoKodDb2Ocsc+fRum/WA/uX/DQ==", V: "今日", M: "Today", RR: "きょう", MM: "Today in toKYO (きょう)", tags: ["T_EX"] },
    { id: "EMouqYScMVM+CcmLQ/CKmCFwZ7JMeg==", V: "今月", M: "This month", RR: "こんがつ", MM: "" },
    { id: "+teq9881o1i/zg1mIr0e6htewLp/IA==", V: "半分", M: "Half", RR: "はんぶん", MM: "" },
    { id: "ssfMMuWRtGbxrr9wwgv+eLfG1PwK5g==", V: "お父さん", M: "Father", RR: "おとうさん", MM: "If there are *two* (よう) people you can trust, your (father) is the *true* (とう) one" },
    { id: "6hoTNzhnDxyHXleDHgVDeGnHbwP8Vg==", V: "冬", M: "Winter", RR: "ふゆ", MM: "Montreal winters be like: FUYU (Fuck You)" },
    { id: "rubZLp5L9okb5IpCam1ZFP8snJxjjw==", V: "北", M: "North", RR: "きた", MM: "When you go far north, it'll be very cold. You need to bring a survival kit (きた)" },
    { id: "NIFBxgmlTOnZ8ob7Y9q2H806gaFpAw==", V: "半", M: "Half", RR: "はん", MM: "" },
    { id: "mtz0xZ/TGQ7uZO8BCw69KDKY7vWFwA==", V: "古い", M: "Old", RR: "ふるい", MM: "When you get old, you had a 'full run' (ふる)" },
    { id: "9JQB6Rl2e3R6Rygxyv5Jg7aSE4bz9A==", V: "中古", M: "Second Hand", RR: "ちゅうこ", MM: "" },
    { id: "40jkqBzCqO6Ezd81xwwgfIt+/WjR8w==", V: "一台", M: "One Machine", RR: "いちだい", MM: "" },
    { id: "HVletaol4VP0U2ldcrL8+oLbaN42uA==", V: "二台", M: "Two Machines", RR: "にだい", MM: "" },
    { id: "ylWRGzD/nlttGCm6QtxMWRvCoWfX6g==", V: "五台", M: "Five Machines", RR: "ごだい", MM: "" },
    { id: "/+ED/NsJ3rtTIKc+B9+lvziM/2QFiA==", V: "十台", M: "Ten Machines", RR: "じゅうだい", MM: "" },
    { id: "7z+JtdYOPP62qfqfEv3mYrUFhURWkw==", V: "外", M: "Outside", RR: "そと", MM: "" },
    { id: "K9Sgt8eToPTLs13Bch/uVZgeMpCRTQ==", V: "外人", M: "Foreigner", RR: "がいじん", MM: "" },
    { id: "q/oss67dVrRoOHp/7LUNGQccmTSsfA==", V: "外れ", M: "Extremity, Furthest point, End, Edge, Limit", RR: "はずれ", MM: "RE: outside, meaning it's edge. If you spawn from there, you'd be (hazıra konmak - はず)" },
    { id: "SSJeyupOHvAqyTpKLknitdQXeCvyiA==", V: "外れる", M: "To be disconnected, to be out", RR: "はずれる", MM: "RE: (reply) outside indicates your compoter disconnected so you can't reply the email" },
    { id: "0D09BJeyGOAx/xKJ5vjZvSWc3bjcIA==", V: "市", M: "City", RR: "し", MM: "" },
    { id: "QDObUXSAl6eSNq20g5oglQiB1W4yrg==", V: "市立", M: "Municipal", RR: "しりつ", MM: "" },
    { id: "lrxUAHiZwIdHqp9JXGsxG+ur1HDn+g==", V: "シアトル市", M: "Seattle", RR: "しあとるし", MM: "" },
    { id: "8A7SPwxpjjcelF1dPLS7nUH/pBrrdg==", V: "広い", M: "Wide, Spacious", RR: "ひろい", MM: "" },
    { id: "W9Fu+hpQNYBPJeHjsmpBLnVAiF3CVQ==", V: "用いる", M: "To Utilize, To Use", RR: "もちいる", MM: "What do you need to utilize something? More cheese of course (もち)" },
    { id: "AdU0PLBTpglJom2Yn56ezRUb/yRC7g==", V: "公用", M: "Government (Official) Business", RR: "こうよう", MM: "Public task is a government business." },
    { id: "Pd3FwmasVcmhYUr+BWMwy7puQJxVTg==", V: "矢", M: "Arrow", RR: "や", MM: "" },
    { id: "0e5e/mU0NE5yClM6n1j7ZX9HEtymfw==", V: "人生", M: "One's Life, Human Life", RR: "じんせい", MM: "" },
    { id: "PbubMtXABQSBDd4t1WjaNt40K5oetQ==", V: "〜台", M: "Big Machine, Number of Machines", RR: "だい", MM: "" },
    { id: "xIcAhOzfNthxQQ2Tp5j9IhWnXixWwA==", V: "今日は", M: "Hello, Good Day", RR: "こんにちは", MM: "" },
    { id: "EtSBwfHtd1IUZljkK+GWUCDGa0kHeA==", V: "用", M: "Task, Business, Purpose, Function", RR: "よう", MM: "" },
    { id: "vt+QsQWcGasbWWZd7cHPAXYSR7oWfg==", V: "戸", M: "Japanese Style Door", RR: "と", MM: "" },
    { id: "Id6iTEhOw6mLIgR57HX+FC2esHemgg==", V: "号", M: "Number, Edition, Model", RR: "ごう", MM: "" },
    { id: "4kpSu82L58D4Oro4mhcSLhv1G5dcMA==", V: "中央", M: "Center, Central", RR: "ちゅうおう", MM: "" },
    { id: "jz6hUKY2USGS1BOW5TdZ8cHVmIuTzw==", V: "打つ", M: "To Hit, To Pound, To Type", RR: "うつ", MM: "After a kid gets hit, they'll use the word 'UF' (う) as an adjective" },
    { id: "GM0BzlwteXjSGo7xlsE3+ede/X/CNw==", V: "一打", M: "Strike, Stroke, Blow", RR: "いちだ", MM: "" },
    { id: "/ATD0gKoh3YLxUYSup2QbQiPOZQWUg==", V: "氷", M: "Ice", RR: "こおり", MM: "" },
    { id: "N+cYN+42wYF+zToVowASu81kDHRXzQ==", V: "かき氷", M: "Shaved Ice", RR: "かきごおり", MM: "" },
    { id: "EHbjdlkSQGavdeLgyyoFHjNAZXkQdg==", V: "申す", M: "To Say Humbly", RR: "もうす", MM: "" },
    { id: "ntUyP3r5b0qDWmqVLjEc1GHuYua2HQ==", V: "申し申し", M: "Hello (telephone)", RR: "もうしもうし - もしもし", MM: "" },
    { id: "zryLpqA47BDGkfk2LoColXahGxnqMA==", V: "子牛", M: "Calf, Baby Cow", RR: "こうし", MM: "" },
    { id: "9cNdVPYfqDgZFOs3Rxb3xBQ882wGYQ==", V: "切手", M: "Postage Stamp, Stamp", RR: "きって", MM: "Post kit - stamp (きって)" },
    { id: "qvCrqFKPbI/Uv6ghwoGl7cIMeGdHOQ==", V: "引き分け", M: "Tie, Draw", RR: "ひきわけ", MM: "Berabere. When you PULL something to SEPERATE them, you're making them even. Hence, Tie / Draw." },
    { id: "PKWpwqMWmmESMdN8rJ97qcPSzy9ugg==", V: "白い", M: "White", RR: "しろい", MM: "" },
    { id: "qSqvTHvUeVlcmVTAC4pGWZwJ3ys6dA==", V: "二十日", M: "Twentieth Day", RR: "はつか", MM: "Twenty hats for the twentieth day" },
    { id: "k7+5EqR7YUsTWeYsDkChpqHi5tkyvA==", V: "丸ごと", M: "In Its Entirety, Entirely, Wholly", RR: "まるごと", MM: "If you go to (ごと) a circle (まる), you need the ENTIRE circle." },
    { id: "e+ry3JzR5C0Kq9ZaheDVXM3ub6MTOQ==", V: "先ず", M: "First of all, To start with", RR: "まず", MM: "First of all, you need to go through the maze (まず)" },
    { id: "6pHlpQ87jmhUpICzMvc+6zCCiMeGkw==", V: "先", M: "Previous, Ahead, Past, Former", RR: "さき", MM: "I was previously a quite (sakin - さき) kid, but then I opened up." },
    { id: "t+buISwwBFFlWS3sbrYmOyGiq6wyRA==", V: "先々月", M: "Month before last", RR: "せんせんげつ", MM: "" },
    { id: "2Jp7jyKSaucC2qjTL0cEhtM/KX2cLQ==", V: "先月", M: "Last month", RR: "せんげつ", MM: "" },
    { id: "faDarTV1eieCtZY5/DuyKNInbPsD+w==", V: "先日", M: "The other day, A few days ago", RR: "せんじつ", MM: "The other day, fuJITSU (じつ) was popular." },
    { id: "/cEq7YFqfN41OBrnJDhgA7nqBqBC7Q==", V: "先生", M: "Teacher, Master, Doctor", RR: "せんせい", MM: "" },
    { id: "7vOWCEWEBTnttQFO8+WwUuCd9yUsmQ==", V: "出かける", M: "To go out", RR: "でかける", MM: "Going out, because there is a DEad (で) body here." },
    { id: "o/RkfBw4F44lS0PfeUAlWdw15ojQ9g==", V: "右手", M: "Right Hand", RR: "みぎて", MM: "" },
    { id: "4NMTgWNau7ZiCFnbET/vaqrhHIbUCg==", V: "四日", M: "Forth Day", RR: "よっか", MM: "" },
    { id: "VQyU3R0ITogXaCeIUUf8THpUJMNQkA==", V: "休み", M: "Rest, Break, Vacation, Holiday", RR: "やすみ", MM: "You'd say 'YASS!! if asked to go on a holiday." },
    { id: "zx6cVCLyrzm5Q4Uc3guUAQnXoqLDJA==", V: "休む", M: "To Rest", RR: "やすむ", MM: "" },
    { id: "JgVXy5cbNHalOlkGM9BUDTc64Pfvuw==", V: "休止", M: "Pause, Rest, Break", RR: "きゅうし", MM: "" },
    { id: "TogiE8kxkmadehrnSEq+KVtVONLjeA==", V: "休日", M: "Holiday", RR: "きゅうじつ", MM: "" },
    { id: "SC+KB7dd2NmrwN1dBYYq8JR20qfv6w==", V: "名人", M: "Master, Expert", RR: "めいじん", MM: "In Medellin (めいじん) there are MASTERS of entertainment." },
    { id: "6iQXsP/GvgDxE2escUGpG74lEcmlPA==", V: "名字", M: "Surname, Last Name, Family Name", RR: "みょうじ", MM: "MY (みょう) last name is..." },
    { id: "rQ3QVqJAgslof+0XxENJwCR0BHi+lA==", V: "字", M: "Character, Letter, Symbol", RR: "じ", MM: "" },
    { id: "DBzBLMds/FtvpuNnBEq/WrXJWrLGrQ==", V: "太字", M: "Bold Letter", RR: "ふとじ", MM: "" },
    { id: "8P/1ff+ASvmFY3Vi1wW6IWerq4DLdA==", V: "文字", M: "Letter (of the alphabet)", RR: "もじ", MM: "Think of eMOJI" },
    { id: "OUOy13pTSQmpMZ53fWyIR15D2BoSdw==", V: "一文字", M: "Straight Line", RR: "いちもんじ", MM: "In もじ reading of もう is shortened. This phrase is obviously longer so you use the longer version, もん." },
    { id: "0aAPwE0z8DbtGNJW8wgB0BI3IVLUiQ==", V: "２０１１年", M: "Year 2011", RR: "にせんじゅういちねん", MM: "" },
    { id: "XpbbYC8F/qL14R4HTWKTN/uqt2ECEg==", V: "年内", M: "Within a year, Within the year", RR: "ねんない", MM: "" },
    { id: "0OJ5jrBpSz+ac+SgQ3Wkf5p8vfT8iQ==", V: "年中", M: "Year Round, All Year, Whole Year, Throughout the year", RR: "ねんじゅう", MM: "" },
    { id: "gWft58GIDvWW5iEBba2saV5cOFTUPA==", V: "一年生", M: "First year student", RR: "いちねんせい", MM: "" },
    { id: "8seTdBV90i9Cx0T562tNXHBM6IIpaQ==", V: "少年", M: "Boy, Young Boy", RR: "しょうねん", MM: "" },
    { id: "blYgna8XOyzsRX6/IxwuQ1jW/uN2ng==", V: "去年", M: "Last Year", RR: "きょねん", MM: "" },
    { id: "HjoSyXEgwWbpdkMobwjp8c69V4031A==", V: "早い", M: "Early, Fast, Quick", RR: "はやい", MM: "HAYAmk (はや) it's too early" },
    { id: "/TJBTrfVzsddtdwz6q2SNPIt2CmWDQ==", V: "早々", M: "As soon as, Just after, Immediately after", RR: "そうそう, はやばや", MM: "If something is early twice, it's obviously important, you gotta do it ASAp" },
    { id: "5dhp9gkdgPQTyixVG6mMY4+qw4nHEQ==", V: "気", M: "Spirit, Energy", RR: "き", MM: "" },
    { id: "isXBC5ejnFoRrAhxmJUEsjJyKBmL3Q==", V: "気に入る", M: "To be pleased / happy / satisfied with", RR: "きないる", MM: "You enter into the energy, you'll be happy with it." },
    { id: "DhlVq99b8uMc85gz9HIMJ2UCX8PSmA==", V: "一気", M: "One breath, One go, One sitting", RR: "いっき", MM: "'One Energy' is weird. What gives you energy, breathing..." },
    { id: "g5fIIS+QVVEjg2COeX+V0EGOwBGu3g==", V: "気分", M: "Feeling, Mood", RR: "きぶん", MM: "PART of your SPIRIT is your mood." },
    { id: "thXlDdydr+PN6lOsm/BNcIboWVFLcg==", V: "人気", M: "Popular, Popularity", RR: "にんき", MM: "benimki populer degil ama seNINKI (にんき) populer." },
    { id: "bFgaGMwPVuX03Y6JvIMXlv3zaaejUg==", V: "元気", M: "Energy", RR: "げんき", MM: "" },
    { id: "ISkGa31Y05cppVIVGFcslJUq5Y65rg==", V: "天気", M: "Weather", RR: "てんき", MM: "Heaven energy determines the WEATHER because heaven is on top of us (不)" },
    { id: "VQvkSb+RPWiLiA5TGtAzExKmkS4c1g==", V: "本気", M: "Serious", RR: "ほんき", MM: "Books are serious matter. Book energy is therefor SERIOUS." },
    { id: "j0N8ZCAJPESsFW4XV0nv0UCz/DZ17g==", V: "平気", M: "Calm, All Right, Okay", RR: "へいき", MM: "When your energy is flat, you're calm." },
    { id: "TwTqDOdzOb4Gxsyejgr8AE1gT9c97g==", V: "一本気", M: "One Track Mind, Single mindedness", RR: "いっぽんぎ", MM: "(Sabit Fikirli)" },
    { id: "IaNch4ymRxF9esqFvOInbW9q1rcpMA==", V: "百万", M: "Million", RR: "ひゃくまん", MM: "" },
    { id: "MOnU8a1yt3yPsvxr+8Stw3MS8Ws8cg==", V: "四百", M: "Four Hundred", RR: "よんひゃく", MM: "" },
    { id: "7vaOB0h2hGbUsJjSrEZqtEECh0jofg==", V: "五百", M: "Five Hundred", RR: "ごひゃく", MM: "" },
    { id: "0KOZxBLyEpeNd6p1iNc62KD9RFUgYw==", V: "二百", M: "Two Hundred", RR: "にひゃく", MM: "" },
    { id: "e4il0OgwXo0DY3ClqevxTjomrRs/YQ==", V: "竹の子", M: "Bamboo Shoots", RR: "たけのこ", MM: "" },
    { id: "NYIvtffWsTjnuwRDysxA5izCAjv0Iw==", V: "竹", M: "Bamboo", RR: "たけ", MM: "" },
    { id: "nQVV+xvI+lgxs9hTtVj32+R+G6GpDQ==", V: "糸", M: "Thread", RR: "いと", MM: "" },
    { id: "lPR3SucH2rpTRF7ZW61EBuwXoawGrQ==", V: "耳", M: "Ear", RR: "みみ", MM: "" },
    { id: "eLlrU5I4JYQ8Z4SfkUFl4Yp1kTjT1A==", V: "虫", M: "Bug, Insect", RR: "むし", MM: "私は虫の女" },
    { id: "oUiYpHv0CO2GLtLEOwv4HmXiFJ+eCg==", V: "村", M: "Village, Rural Town", RR: "むら", MM: "" },
    { id: "w91gQhmhm3mPqYxQWsaKgEgnTIAj9g==", V: "村人", M: "Villager", RR: "むらびと", MM: "" },
    { id: "sspUlHsw/3t3vhC0od/+iXDMpFgbnw==", V: "男", M: "Man", RR: "おとこ", MM: "Men are into Cars (おと) from childhood (こ)" },
    { id: "m52KDx1kPNdKd/lXvvZVGRk7+G0hzw==", V: "町", M: "Town", RR: "まち", MM: "Towns have football teams, and host MATCHes (まち)." },
    { id: "z817TF2pVypU9Gmrf2TeTvoJkzN4eg==", V: "見る", M: "To see, To look", RR: "みる", MM: "" },
    { id: "oONEmS90STw0p4vzYiDl0Mu0ERsZ8A==", V: "見える", M: "Can see, visible", RR: "みえる", MM: "" },
    { id: "7l0cMIA+qCGqGi2gO7aEh2EsemKcfw==", V: "見せる", M: "To show", RR: "みせる", MM: "" },
    { id: "45JHFJ0SFfoTvwNVoR4B4XaR9hEuDQ==", V: "見分ける", M: "To distinguish, To tell apart", RR: "みわける", MM: "" },
    { id: "y2Evj0VCMC8xOpPOSB5+jhzVVgKqKA==", V: "花", M: "Flower", RR: "はな", MM: "" },
    { id: "xV4Tr0OJn00xnY/lAIG0AmKSjLkluw==", V: "花火", M: "Fireworks", RR: "はなび", MM: "" },
    { id: "bvqCn0qp+R1dPxMJbysoWM+f28mj3Q==", V: "花見", M: "Viewing cherry blossoms, sakura viewing", RR: "はなみ", MM: "" },
    { id: "J6iFQkcr01QH545zuAVDSuLnCsYtOw==", V: "見方", M: "Way of seeing, Point of view", RR: "みかた", MM: "If you don't share a point of view with people, they'll try to change yours with a SWORD (かた)な" },
    { id: "6tpdgllCSYtW3H0SDLOeyHYfI9rHjQ==", V: "月見", M: "Moon viewing", RR: "つきみ", MM: "" },
    { id: "1SFCVNIwsUTepde778gp6Z2Pz21IMw==", V: "貝", M: "Shell, Shellfish, Clam", RR: "かい", MM: "" },
    { id: "tdfh+uedqOTYiruSavEsOjTnINv0PQ==", V: "赤", M: "Red", RR: "あか", MM: "" },
    { id: "JQX/BI/yGGSceiGycyOC2qgviWRESg==", V: "赤ちゃん", M: "Baby", RR: "あかちゃん", MM: "" },
    { id: "AVyF6xDDetbrIm6K97gPeKeZ8rjodw==", V: "足りる", M: "To be enough, suffice", RR: "たりる", MM: "TAmam (た) yeterli." },
    { id: "MgzlA57XCmlEuJVrAnTQpyYhctFojA==", V: "足", M: "Foot, Leg", RR: "あし", MM: "What's in the foot? ASIl tendon (あし)" },
    { id: "7zg31Wlltt/zJNXM6wIOt5NgsaS/EQ==", V: "不足", M: "Shortage, Insufficient, Not enough", RR: "ふそく", MM: "" },
    { id: "dk4n1virGVt1xA2IeaXVvMMLQjlURA==", V: "車", M: "Car", RR: "くるま", MM: "When car's wind shields gets wet, they just won't dry (KURUMAz - くるま)" },
    { id: "LyDge8FmYYbDMXICT5OTSx3CX18yYg==", V: "車内", M: "Inside the car", RR: "しゃない", MM: "" },
    { id: "154FoDLz5seQPGG1LsmhRIi8s07jrw==", V: "世", M: "World, Society, Age, Generation", RR: "よ", MM: "The new generations greeting be like: 'Yo!" },
    { id: "F9FeMGh+wgvsCufVkHUhOt1enydmKw==", V: "二世", M: "Second Generation", RR: "にせい", MM: "" },
    { id: "qoUEgr4lpVoemZk74aqzwvLW9dTp2Q==", V: "三世", M: "Third Generation", RR: "さんせい", MM: "" },
    { id: "CmqISZnv9qPOrSYErK3/cqv51fgaHg==", V: "仕方", M: "Method, Way, Way of doing", RR: "しかた", MM: "If you have a different way of doing things, they will make you do it their way using a sword (KATAna - かた)" },
    { id: "00rhfILT1zTeYwMz19hQYZODEsUi6A==", V: "他", M: "Other", RR: "ほか", MM: "Don't smoke non-flavoured HOOKAH (ほか) when there are many OTHER flavours you can choose from." },
    { id: "u6YWBGxc2/bb5++fHr+2wyKreeR6Lg==", V: "他人", M: "Another person, Stranger", RR: "たにん", MM: "While I'm studying Japanese, ANOTHER PERSON might be TANNING (たにん) at the beach." },
    { id: "vkot70MjZ6B3IxKZoQaRrjQLYijq2w==", V: "代わる", M: "To Replace", RR: "かわる", MM: "You replace the muKAVVA (かわ) when it gets old" },
    { id: "1BfSx90JPubB4nWRZSbCTtgXKoGj3Q==", V: "一代", M: "Lifetime", RR: "いちだい", MM: "" },
    { id: "X/8k97D2txvNUBhgyAXuRmvb+xAlOg==", V: "代用", M: "Substitution", RR: "だいよう", MM: "Task of substuting is substitution." },
    { id: "asMhVCRlfW0TpxJMk6OWonGcfpeCBQ==", V: "写す", M: "To copy, To photograph, To take a picture", RR: "うつす", MM: "To copy Sue, you have to hit (うつ) sue first." },
    { id: "LV297kmo+xyupkglUI5qq3tVPG2mfw==", V: "写る", M: "To be photographed", RR: "うつる", MM: "You think it's RUde (る) if someone was photographing you. So you hit them (うつ)" },
    { id: "kSzsJvq6QigQuXR+qtKjjXSNP4vXRg==", V: "平ら", M: "Flat", RR: "たいら", MM: "You have a FLAT TIRE (たいら)" },
    { id: "tPSV9Ki4BPNip+vq4FO6pk8zyeP62A==", V: "平日", M: "Weekdays", RR: "へいじつ", MM: "Week days are flat days..." },
    { id: "LDwY2X1rjW+e9xSOec88eN0GAwVTxQ==", V: "皿", M: "Plate, Dish", RR: "さら", MM: "" },
    { id: "8rBOAx6EQ+3bdPqFwX/vpzPtFw3UwQ==", V: "小皿", M: "Small Plate, Small Dish", RR: "こざら", MM: "" },
    { id: "Iw8MPMPhSiLNemxY8SAu77InDW68bA==", V: "お礼", M: "Thanks, Gratitude", RR: "おれい", MM: "" },
    { id: "TO7h0p45MdpivObNMZbRkKrsY2LYVw==", V: "不正", M: "Injustice, Unfairness, Dishonesty", RR: "ふせい", MM: "HUSEyIn (ふせい) çok şerefsiz adam ya..." },
    { id: "aPH3flmH4S70dsp0oqtaG3bg+CB8uw==", V: "年", M: "Year", RR: "とし", MM: "My new YEAR resolution is stop being TOO SHY (とし) next year." },
    { id: "gRal2T3wmLlsvtYPeZmKihTXKwZ9cw==", V: "名", M: "Name, Reputation", RR: "な", MM: "" },
    { id: "tHTmMwA6i4tfWX/9ensVAlYnF2MJMA==", V: "宝", M: "Treasure", RR: "たから", MM: "People buy a piece of 宝石 (ie. treasure) and put it on the bride (TAKARlAr - たから)." },
    { id: "5Ibjt5CXhNn985c7NU2dqPe2gnTNAQ==", V: "宝石", M: "Jewel", RR: "ほうせき", MM: "" },
    { id: "pzWWUExQeCI5X/u3Flfh5zAaUIfsRg==", V: "赤い", M: "Red", RR: "あかい", MM: "" },
    { id: "Ws2tvIeqhRWtT/1mQBhT+uy6jCHFIw==", V: "百", M: "Hundred", RR: "ひゃく", MM: "" },
    { id: "5tZYVRNC0/Wx3dNaPGqQ1K6vezOrPw==", V: "大気", M: "Atmosphere", RR: "たいき", MM: "" },
    { id: "AuRq7qdP8aUjyKgBsf3ym6jzJTnQow==", V: "四つ", M: "Four things", RR: "よっつ", MM: "" },
    { id: "HEpCclr2yGaYKwxWaHjFN5+zdWGF8A==", V: "四千", M: "Four thousand", RR: "よんせん", MM: "" },
    { id: "QkAmo0dqeuZFZNTR0dEelPvuhcz1Vw==", V: "四十", M: "Fourty", RR: "よんじゅう", MM: "" },
    { id: "WQGDA+T7u6VN186sb43RXE00BCBWqw==", V: "左手", M: "Left hand", RR: "ひだりて", MM: "" },
    { id: "Qbp5X06OMKt6tj3c75NaniIiKYWEqw==", V: "石", M: "Stone", RR: "いし", MM: "Think of sexy (せき) girl, now think of the word 'delicious' (おいし), then remove the お and there you have it." },
    { id: "jW/7YU37WXIdLLH/YDEKk9VOepgKnQ==", V: "主に", M: "Mainly, Primarily", RR: "おもに", MM: "To remove stains from your clothes, MAINLY you should use OMO (おも)" },
    { id: "0MvasNoQNZmIbgJaFoY3cDy5eD1ttw==", V: "主人", M: "Head Of Household, Husband, Landlord, Master", RR: "しゅじん", MM: "" },
    { id: "o2FAczmpr24cLQmFk/44MLVD0UOIWg==", V: "男の子", M: "Boy", RR: "おとこのこ", MM: "" },
    { id: "rGEhaMngTqrDyp9iSuVcQocnkyoHeg==", V: "毛虫", M: "Caterpillar", RR: "けむし", MM: "" },
    { id: "uO24mJJv0fZ8sL0WykmrcUSo/Fk+Eg==", V: "下町", M: "Downtown, Backstreets", RR: "したまち", MM: "" },
    { id: "m1HkM9dh1JSkLsCW8Z2tnjic6mOBpw==", V: "男の人", M: "Man", RR: "おとこのひと", MM: "" },
    { id: "X0I9jIQ/go9dc5jdiwlTG6iAO4p8OQ==", V: "今まで", M: "Until Now, So Far", RR: "いままで", MM: "UNTIL NOW, I've never talked to an IMAM" },
    { id: "4Iei4D9rLcKthJkDsq+ITGk0P6xvhw==", V: "毛糸", M: "Wool Yarn, Yarn", RR: "けいと", MM: "" },
    { id: "aONsyDvItI/sTw6Y/CLrRwhMn2lVCw==", V: "今すぐ", M: "At once, Right now, Immediately, Right away", RR: "いますぐ ", MM: "" },
    { id: "hShWQCPn+W2/QBu1HXPM2AYmcmiexQ==", V: "万人", M: "All people, Everybody", RR: "ばんにん", MM: "" },
    { id: "hCLlS6Xlcs7MbTO4XWdigrLj7nUQZA==", V: "一生", M: "Whole life, A lifetime", RR: "いっしょう", MM: "If you want to spend a LIFETIME with a person, you SHOUld (しょう) treat them well." },
    { id: "2xJKnQ3ib8rs1jAsmTcZO5Lfdn+y9Q==", V: "生える", M: "To grow", RR: "はえる", MM: "え gives a verb a meaning of 'making it happen'. What happens when you make life happen? You GROW" },
    { id: "hcVmgk5IYuSloclm/hPX6xL60wm4Zw==", V: "生まれ", M: "Birth, Birthplace", RR: "うまれ", MM: "It's like the verb 'to be born - うまれる' but without the る it's your birth place (or birth)" },
    { id: "Ay8wcX4ODo/2a4uOE5t/ALMpOE3njA==", V: "兄", M: "Older Brother", RR: "あに", MM: "To your older brother you say FU(きょう) ~ (あに)na koyayım..." },
    { id: "z2bznKhJN84JaIAsa7pKlMg7mj48vw==", V: "皮", M: "Skin, Hide", RR: "かわ", MM: "Things are COVERed (かわ) with skin." },
    { id: "+p2TdP+FbppkCL0tJO6UwS9OcI+hnQ==", V: "交ぜる", M: "To Mix", RR: "まぜる", MM: "In a MAZE (まぜる) you would mix up your direction." },
    { id: "I92vVaoITa80k0Iz6ozEsAqTscdg7g==", V: "光", M: "Light, Sunlight", RR: "ひかり", MM: "Sunlight -> beach -> 'Hiii!.. karı'" },
    { id: "gDLsyfjbmOyFktCQoPcan8E7e6sosA==", V: "光年", M: "Lightyear", RR: "こうねん", MM: "" },
    { id: "tLJiBplxNzxjJh+YpiC7UFqMSrktow==", V: "月光", M: "Moonlight", RR: "げっこう", MM: "" },
    { id: "2eR7sIvhnrMFlaO3NAjyyrDQMMwOHg==", V: "日光", M: "Sunlight", RR: "にっこう", MM: "" },
    { id: "2hM1vI+JFWLumhiqsRcz2IuZ0zOVNg==", V: "〜回", M: "Number of times", RR: "かい", MM: "" },
    { id: "UdvRqaCgj3BrHnQh+qZSeOtS3O64pg==", V: "回る", M: "To Revolve, To go around, To rotate", RR: "まわる", MM: "Rotating table (ie. MASA ~ まわ)" },
    { id: "viwVew4uKmntgLXp8LxKvwWhZ/NmtA==", V: "一回", M: "One time", RR: "いっかい", MM: "" },
    { id: "oKhkmPODHlFc8aKES3XobWJrEKeBCw==", V: "今回", M: "This time", RR: "こんかい", MM: "" },
    { id: "l09TxtCXA50+cJHycTj4xyc4/x4+Mg==", V: "多い", M: "Many, Lots of", RR: "おおい", MM: "When there are too many of something, you get suprised and say 'OOoo!'" },
    { id: "pHqj5idUNH8LncqLp72yOOJ7L5xLKA==", V: "多分", M: "Maybe, Perhaps, Probably", RR: "たぶん", MM: "You have many parts to choose from, MAYBE you'll pick the best one." },
    { id: "Rdk0bkoib9xQDPDlxsveqIya3AuM0Q==", V: "林", M: "Forest", RR: "はやし", MM: "" },
    { id: "5Siz04s7LRDJJjB13JcwgxQYh3NeiQ==", V: "空気", M: "Air, Atmosphere", RR: "くうき", MM: "" },
    { id: "E1fAyfqZVwKKzruHVACw7iN7qtEDwA==", V: "空", M: "Sky", RR: "そら", MM: "Best weather is くう (dry) and then (SOnra), KARA (~ そら)" },
    { id: "PnCg8YZWfPliGI40M9bh5kYLa0zWIQ==", V: "音", M: "Sound, Noise", RR: "おと", MM: "おん (ON) - OY, おと (~ OnTO) - KY" },
    { id: "TwblEAIIz1jXjZX7kob8moYJ64cgAQ==", V: "体", M: "Body", RR: "からだ", MM: "The body should be on land (KARADA - からだ)" },
    { id: "/9FoOi2mrcMOcl85Mz5MecNNcUqFXw==", V: "体力", M: "Physical Strenght, Stamina, Endurance", RR: "たいりょく", MM: "" },
    { id: "sVLiCCSYm7Ilqst4OI7GAIL4AGruEg==", V: "体内", M: "Internal, Inside the body", RR: "たいない", MM: "" },
    { id: "ZksuM/w6As1Lz0biPinbIaDtVqXbUQ==", V: "声", M: "Voice", RR: "こえ", MM: "" },
    { id: "Sm5xzkd7e4kC8+hkuBnvSlG//Ya4pQ==", V: "大声", M: "Large Voice, Loud Voice", RR: "おおごえ", MM: "" },
    { id: "sNK1RszYJC006ZtQKITu35jbtWMZpA==", V: "来る", M: "To Come", RR: "くる", MM: "When you come it's usually wet, not dry (KURU - くる)" },
    { id: "w5S2aRg7WFG4b3XgchKM+0GWiHcLCA==", V: "来月", M: "Next month", RR: "らいげつ", MM: "" },
    { id: "F8hJNmrw7FX1miChPhI4/9HSrOdRkA==", V: "来年", M: "Next year", RR: "らいねん", MM: "" },
    { id: "/mSfp0dBdPWgHFLMdYbTdgzElR5ogw==", V: "古来", M: "Ancient", RR: "こらい", MM: "" },
    { id: "jBBWBcJS+5HflZM0xXOTqeWoKv+uLQ==", V: "外来", M: "Imported, Foreign", RR: "がいらい", MM: "" },
    { id: "j3rMv87CrlevyPKZbyhYfFCdqLQvkQ==", V: "〜年来", M: "For some years", RR: "ねんらい", MM: "" },
    { id: "5wCm6Z5HCq9b8efmxkM/SS2F+S0VIQ==", V: "角", M: "Angle, Corner", RR: "かく (angle), かど (corner)", MM: "" },
    { id: "xSwPqUEMv77nOsC8uBK0AFEqRnadJQ==", V: "三角", M: "Triangle", RR: "さんかく", MM: "" },
    { id: "1Qm12t6tmwyuRshqnnJ29Pobeh78cw==", V: "四角", M: "Square", RR: "しかく", MM: "" },
    { id: "obf5Mq70etbsbVN740q/Zisl6LFB2w==", V: "谷", M: "Valley", RR: "たに", MM: "" },
    { id: "+OmuW3JSpj2UxHEOQrFYjtkaN53dmQ==", V: "空車", M: "Free Taxi, Empty Parking Space, Free Cab, Available Taxi, Available Cab", RR: "くうしゃ", MM: "When a car has sky in it, it's empty (ie. available)" },
    { id: "it7Irqbdd6fHQ+ztSS7ZZSVhPJSoAQ==", V: "外交", M: "Diplomacy", RR: "がいこう", MM: "" },
    { id: "75G+uaC5KZEQrDe2fKiWwr8TMETbTQ==", V: "大体", M: "General, Approximate, Outline, Gist", RR: "だいたい", MM: "If all you can see is a big body of a person, then you'll only have a general idea of what they look like. You know their outline is quite big, but you don't know anything else." },
    { id: "9IgAFFcCUItYfdWHqMb1PxLWB3QcMQ==", V: "本来", M: "Originally, Primarily, Essentially, Naturally", RR: "ほんらい", MM: "" },
    { id: "paX3leDJWmcKCNDr7nv8+hPtbt55xA==", V: "大会", M: "Convention, Tournament, Meetup, Event", RR: "たいかい", MM: "Big meetup is a convention." },
    { id: "8fPaS6wxSycLYbngheWZertQdkk2nA==", V: "会う", M: "To Meet, To Encounter", RR: "あう", MM: "When you meet someone, you go 'Aaa'" },
    { id: "YAvYI7zgQSs+LK7Z2quAk1ie+nf2Kg==", V: "同じ", M: "Same", RR: "おなじ", MM: "どう -> Döner -> Dona -> おな" },
    { id: "UPXQ4YWKtLDtrhwlA+PBpB2DT9KmuA==", V: "同日", M: "Same day", RR: "どうじつ", MM: "" },
    { id: "Wl38USxIyOZJB+Z2MueP0hGMtRutaQ==", V: "毎回", M: "Every time", RR: "まいかい", MM: "" },
    { id: "c/z3jUvNTRgxXvRwlriKTelWmvH5Iw==", V: "当たる", M: "To be on target", RR: "あたる", MM: "aTAru - on TArget. When you're CORRECT, you go 'Aaa あ'" },
    { id: "2uiQT8MSdV6Utc1CsLkHwx4csx2opA==", V: "当たり", M: "A success", RR: "あたり", MM: "" },
    { id: "+P9LhVxA3TOYGY+gLmV42N1dRE+lug==", V: "毎月", M: "Every month, Monthly", RR: "まいつき", MM: "" },
    { id: "IjXO+1U/8cC58P/hp9N38BNgYvWVcw==", V: "毎日", M: "Every day, Daily", RR: "まいにち", MM: "" },
    { id: "Ck5Pqd5MBY6+e2an+ryt49j3MqHiHg==", V: "毎年", M: "Every year, Yearly", RR: "まいねん", MM: "" },
    { id: "OT2cQrXTwdp4gmTO52K3fpFO+hWmdw==", V: "米", M: "Rice", RR: "こめ", MM: "This kanji almost looks like the COME ~こめ (来) kanji" },
    { id: "cZBcpMRWcJ8oNJ9Djr2NfV5j8KKncw==", V: "羽", M: "Feathers", RR: "はね", MM: "Ha? Ne?" },
    { id: "2lCK/9QTmQlKwy2nupoYy7KTyKafCA==", V: "考える", M: "To think about, To consider, To give some thoughts", RR: "かんがえる", MM: "Who would you consider ? Your kanka (かんが)" },
    { id: "ZrngX5gvjJ+3yEFHU5VTo/3IjxgibQ==", V: "肉", M: "Meat", RR: "にく", MM: "" },
    { id: "AsgJMgTG7eaCdjd31WDZEP3NRvY2hg==", V: "牛肉", M: "Beef", RR: "ぎゅうにく", MM: "" },
    { id: "ax6o/Bk7jJCqoSpcg2oAfeAsU3qrDg==", V: "皮肉", M: "Irony, Sarcasm", RR: "ひにく", MM: "Skin meat... Skin doesn't have meat... Oh the IRONY :D" },
    { id: "UJgP3a6SLytjs8gLbdbZ+ItNedpIRQ==", V: "自分", M: "Oneself, Myself, Self", RR: "じぶん", MM: "" },
    { id: "DDHkL4zV0L/Tgy9h1lsCTVhgYiM07w==", V: "自立", M: "Independance, Self reliance", RR: "じりつ", MM: "" },
    { id: "2qh2Hcf702gubHlB3e98/jxEiqfmuw==", V: "色", M: "Color", RR: "いろ", MM: "" },
    { id: "0tvWv47Xr3UEbiCo5zyvN/W84xIu/A==", V: "色々", M: "Various", RR: "いろいろ", MM: "" },
    { id: "xQ0EIn+8QwUt/YyCMFl2p2qnUMuOkQ==", V: "水色", M: "Sky Blue, Light Blue", RR: "みずいろ", MM: "" },
    { id: "6nFl9SFbszLMSvV8mfPGgQM5KRsWgg==", V: "行く", M: "To go", RR: "いく", MM: "Turkish slang: To Go = (I)kilemek - い" },
    { id: "Rx2VDgbeKkbqVCc5dxyN/KXDNVxSyA==", V: "行う", M: "To carry out a task, To perform", RR: "おこなう", MM: "To GO with a task. You say 'OKAY NOW' (おこな) before starting a task." },
    { id: "yr016wknq5cEAXeKuhiwnWvnEUHLzA==", V: "行き", M: "Train Direction. Bound For", RR: "ゆき, いき", MM: "Bound for toKYo (き) station, heading to meet YUKI (ゆき)." },
    { id: "DUET/oAVo515S7fgSe8KZJfXq9sMig==", V: "西", M: "West", RR: "にし", MM: "Japan imported all their SHEep from the WEST, because they had No SHEep ~(にし)" },
    { id: "TGE+9ESi+Blc6yEb83Lcs4BjrSrgpQ==", V: "北西", M: "North West", RR: "ほくせい", MM: "" },
    { id: "RAhXHiD6HzwSkv6BcgFZP1AIuPTDzg==", V: "何千", M: "Thousands", RR: "なんぜん", MM: "" },
    { id: "n56oFqK1UnBakXRpIkDF/JBrbkLLxg==", V: "何", M: "What", RR: "なに, なん", MM: "" },
    { id: "abpXLpa+akaAzvePsy10SeE/rprkXw==", V: "何人", M: "How many people", RR: "なんにん", MM: "" },
    { id: "t3BZzA9IvTVfcVbUlWR/Gc5gFbHSxA==", V: "何月", M: "What month", RR: "なんがつ", MM: "" },
    { id: "CqIHAfyuEhngZ2EAlHNnOjQMko9oBw==", V: "何日", M: "How many days, Which day", RR: "なんにち", MM: "" },
    { id: "HAIptOI65okwvGVgAz8bIsvjv99h/Q==", V: "何年", M: "What year, How many years", RR: "なんねん", MM: "" },
    { id: "q/62aEdk3Fz2oYi3+1WB4HMpIc1vOA==", V: "何回", M: "How many times", RR: "なんかい", MM: "" },
    { id: "FHRdIZZdrIHILl/N3GqY/FECb54Mgg==", V: "学ぶ", M: "To learn, To study", RR: "まなぶ", MM: "If you don't learn and study, you'll become a MANAv (まな)" },
    { id: "Z9P77VtFExQ29VrDxAxeVjagBWFQlQ==", V: "学生", M: "Student", RR: "がくせい", MM: "" },
    { id: "RODJOSzplZeUzrryFz3r82rL3ebZKA==", V: "学年", M: "School Grade, School Year", RR: "がくねん", MM: "" },
    { id: "YmrbpYsxLcu6revuG3lPKcO3lTcVZg==", V: "入学", M: "School Admission", RR: "にゅうがく", MM: "" },
    { id: "P8aOG+lHryEqLg3jVPjyIKrByn921g==", V: "工学", M: "Engineering", RR: "こうがく", MM: "" },
    { id: "7hOC6kl4ZXwCxuDB03WLvTcuiYaKUA==", V: "大学", M: "University", RR: "だいがく", MM: "In Uni you either DIE (だい) or graduate." },
    { id: "K/MFfxCss0QNYepjNMqAt8Z6I6SS/A==", V: "休学", M: "Absent From School, leave of absence", RR: "きゅうがく", MM: "" },
    { id: "W7Xh5vUouCFiGf6IEOtOPgyaz5ZfpA==", V: "金", M: "Gold", RR: "きん", MM: "" },
    { id: "4ZvYwpx84bxT203FZDpLlHXOq5ep+A==", V: "金玉", M: "Testicles", RR: "きんたま", MM: "" },
    { id: "Ju4dkQGeKqxmQX8i7gOgM5ofkVVgUw==", V: "お金", M: "Money", RR: "おかね", MM: "Money is associated with Kings (きん) and Blood (かね)" },
    { id: "3evC/tNy/8Du3d99pJmqIThnG3eEnw==", V: "雨", M: "Rain", RR: "あめ", MM: "" },
    { id: "zgK9yuReVueEKU/76whjzAaren9Qog==", V: "青い", M: "Blue", RR: "あおい", MM: "" },
    { id: "anYNanBR6gFMk/KZ4EtC/uBNlcFgcg==", V: "青年", M: "Youth, Young man", RR: "せいねん", MM: "" },
    { id: "e2l4IUQwSwtdWRSvkf0RU0yzEB9PtQ==", V: "草", M: "Grass", RR: "くさ", MM: "" },
    { id: "y+/gNwQFXbr1u1ChnnZqZUm7Jum2nQ==", V: "図", M: "Diagram", RR: "ず", MM: "" },
    { id: "t1CQOiUFRNm1ELYetxjXNm/z7bK82w==", V: "弟", M: "Younger Brother", RR: "おとうと", MM: "You have an AUTHORITY (おとうと) over your younger brother" },
    { id: "UvTJyCNvj8m/uUtjhZoIt5VLL5h0XA==", V: "兄弟", M: "Brothers, Siblings", RR: "きょうだい", MM: "" },
    { id: "kWVUFMT1zvK0TKDoDS0qBXiKtsy4Yg==", V: "作る", M: "To make, To build, To create", RR: "つくる", MM: "You're the key master, you can make keys: ie. TUZU KURU (つくる)" },
    { id: "hsDGeT/OvzrM0kp6lR/PKBIWSX/Uug==", V: "作文", M: "Composition, Writing, Essay", RR: "さくぶん", MM: "" },
    { id: "HKIqN+4XP6jCnjr8zM7S16N9HVb3zw==", V: "作用", M: "Action, Effect, Operation", RR: "さよう", MM: "" },
    { id: "p8VV0ndRRroEIRDnkjC2eAUog6qvBA==", V: "工作", M: "Construction, Handicraft", RR: "こうさく", MM: "" },
    { id: "7yDoQwRYk+hT7E97/qfKp8Zgrij3fg==", V: "大作", M: "Epic, Masterpiece", RR: "たいさく", MM: "" },
    { id: "1XVXQVond8JV8v2HEJXbozvvUbVRPg==", V: "社内", M: "Within the company, In house", RR: "しゃない", MM: "" },
    { id: "QSRK00hDbrlZQVd/MEIWGM9r7SDTzg==", V: "入社", M: "Joining a company", RR: "にゅうしゃ", MM: "" },
    { id: "zNbhtW3wxxdm9VydqYFzX8TUc2AAHg==", V: "公社", M: "Public Company, Government Agency, Federal Agency", RR: "こうしゃ", MM: "" },
    { id: "XqjJ2WQSw3k7Zk1XXZPgvh/AE/fBGg==", V: "本社", M: "Headquarters, HQ", RR: "ほんしゃ", MM: "" },
    { id: "XAw3pypxtzS1hvGlamZwXoP1fKS79w==", V: "会社", M: "Company, The office", RR: "かいしゃ", MM: "" },
    { id: "MHw8zkfVGTTBuDki0ZAdxEcYzDGJFQ==", V: "言う", M: "To Say", RR: "いう", MM: "That's the い from といます (ie. I am)" },
    { id: "WRkqTjjDQoB76KzKjavxM2UrvsjDUg==", V: "走る", M: "To run", RR: "はしる", MM: "What do you run with? Your foot (あし)" },
    { id: "w4z+N61sy/jDQh9JOr6SXIpBRRfbyg==", V: "走行", M: "Traveling, Running, Moving", RR: "そうこう", MM: "When you travel to a cold place, it'll be SO (そう) COld (こう)" },
    { id: "/YRl9s38bEkQcn6arZ/RmCoXCeEYkg==", V: "近い", M: "Close, Near, Nearby", RR: "ちかい", MM: "Meeting (かい) with that chick (ち) nearby." },
    { id: "py70p4knrpu97UR95wgwr5WxOz676A==", V: "近日", M: "Soon, In a few days, Coming days", RR: "きんじつ", MM: "" },
    { id: "1L6Q1X8yGjMHMvnfIeot1AsaQQVBfw==", V: "近年", M: "Recent Years", RR: "きんねん", MM: "" },
    { id: "/cnCfvMh99ji5p4bZ/XH1zb92GFIsA==", V: "麦", M: "Wheat, Barley, Oats", RR: "むぎ", MM: "" },
    { id: "IIHUz51WyiHgVMHnAiSDZ5D+XSIdYQ==", V: "里", M: "Home Village, Hometown", RR: "さと", MM: "" },
    { id: "ZvE+zYiZWDNymUkqIqRP6fNUh2S/pQ==", V: "里心", M: "Homesick", RR: "さとごころ", MM: "" },
    { id: "TuGWwPuBFqAr8Zi0r+ZXFsPlidun8g==", V: "本当", M: "Reality, Truth", RR: "ほんとう", MM: "" },
    { id: "iFgN8QfK8oAforqhAprWeoBLCmjIhw==", V: "会", M: "Meeting, Party", RR: "かい", MM: "" },
    { id: "sQB1KMVr6AK0D83ls3hEWUJeB/irCQ==", V: "考古学", M: "Archeology", RR: "こうこがく", MM: "" },
    { id: "Jhb3X6MRj9vnawUua14S22Yga6/T4g==", V: "仕草", M: "Action, Gesture, Treatment, Movement", RR: "しぐさ", MM: "" },
    { id: "VlElvDhspK58/+epaJzxM8NWUN6t4Q==", V: "〜形", M: "Form, Tense", RR: "けい", MM: "" },
    { id: "wjM5ZurrWZ0mCIYCfQbBz5b9SNirWQ==", V: "文学", M: "Literature", RR: "ぶんがく", MM: "" },
    { id: "HOPP9Zjjs0+fLmFevrDyaQBHyU/Bnw==", V: "〜斤", M: "Bread Loaf Counter", RR: "きん", MM: "" },
    { id: "VFrlwq301Xoln3dhSALGP3RH0BzCuA==", V: "大文字", M: "Uppercase Letters", RR: "おおもじ", MM: "" },
    { id: "ooZQ8E6EVlymKS3IVSLNtKzgfN/Jqw==", V: "耳打ち", M: "Whisper in ear", RR: "みみうち", MM: "" },
    // { id: "", V: "", M: "", RR: "", MM: "" },
  ]
}
