export default {
  id: "vocab",
  title: "Vocabulary 単語",
  description: "Study set that includes cards to / from vocabulary words.",
  topic: "japanese",
  flashcards: {
    "3UNJQV1ZhNMhiodJHR9RUzcJrIYKAg==": true,
    "JWaBtSN/LhH2FY9OtNEUGhtzlrbSkg==": true,
    "XgJBDHSMuPmtu3cIccMGTNLHQ+1YiQ==": true,
    "aHaaBZn7/QudfhNPOIh4HpWXpMsmqw==": true,
    "Rrh0lq/wRfXLXR2N6TvrFH8b2ZKCYA==": true,
    "ay0jJE81SFepPQHvlTavSmYTnP4MrQ==": true,
  },
  data: [
    { id: "UcMbHoTfSs/ZGHYCZUZXr2zSvK2SjQ==", V: "今", M: "Now", RR: "いま", MM: "'Imma' do it NOW!" },
    { id: "3572AoKodDb2Ocsc+fRum/WA/uX/DQ==", V: "今日", M: "Today", RR: "きょう", MM: "Today in toKYO (きょう)", tags: ["T_EX"] },
    { id: "EMouqYScMVM+CcmLQ/CKmCFwZ7JMeg==", V: "今月", M: "This month", RR: "こんがつ", MM: "" },
    { id: "+teq9881o1i/zg1mIr0e6htewLp/IA==", V: "半分", M: "Half", RR: "はんぶん", MM: "" },
    { id: "ssfMMuWRtGbxrr9wwgv+eLfG1PwK5g==", V: "お父さん", M: "Father", RR: "おとうさん", MM: "If there are *two* (よう) people you can trust, your (father) is the *true* (とう) one" },
    { id: "6hoTNzhnDxyHXleDHgVDeGnHbwP8Vg==", V: "冬", M: "Winter", RR: "ふゆ", MM: "Montreal winters be like: FUYU (Fuck You)" },
    { id: "rubZLp5L9okb5IpCam1ZFP8snJxjjw==", V: "北", M: "North", RR: "きた", MM: "When you go far north, it'll be very cold. You need to bring a survival kit (きた)" },
    { id: "NIFBxgmlTOnZ8ob7Y9q2H806gaFpAw==", V: "半", M: "Half", RR: "はん", MM: "" },
    { id: "mtz0xZ/TGQ7uZO8BCw69KDKY7vWFwA==", V: "古い", M: "Old", RR: "ふるい", MM: "When you get old, you had a 'full run' (ふる)" },
    { id: "9JQB6Rl2e3R6Rygxyv5Jg7aSE4bz9A==", V: "中古", M: "Second Hand", RR: "ちゅうこ", MM: "" },
    { id: "40jkqBzCqO6Ezd81xwwgfIt+/WjR8w==", V: "一台", M: "One Machine", RR: "いちだい", MM: "" },
    { id: "HVletaol4VP0U2ldcrL8+oLbaN42uA==", V: "二台", M: "Two Machines", RR: "にだい", MM: "" },
    { id: "ylWRGzD/nlttGCm6QtxMWRvCoWfX6g==", V: "五台", M: "Five Machines", RR: "ごだい", MM: "" },
    { id: "/+ED/NsJ3rtTIKc+B9+lvziM/2QFiA==", V: "十台", M: "Ten Machines", RR: "じゅうだい", MM: "" },
    { id: "7z+JtdYOPP62qfqfEv3mYrUFhURWkw==", V: "外", M: "Outside", RR: "そと", MM: "" },
    { id: "K9Sgt8eToPTLs13Bch/uVZgeMpCRTQ==", V: "外人", M: "Foreigner", RR: "がいじん", MM: "" },
    { id: "q/oss67dVrRoOHp/7LUNGQccmTSsfA==", V: "外れ", M: "Extremity, Furthest point, End, Edge, Limit", RR: "はずれ", MM: "RE: outside, meaning it's edge. If you spawn from there, you'd be (hazıra konmak - はず)" },
    { id: "SSJeyupOHvAqyTpKLknitdQXeCvyiA==", V: "外れる", M: "To be disconnected, to be out", RR: "はずれる", MM: "RE: (reply) outside indicates your compoter disconnected so you can't reply the email" },
    { id: "0D09BJeyGOAx/xKJ5vjZvSWc3bjcIA==", V: "市", M: "City", RR: "し", MM: "" },
    { id: "QDObUXSAl6eSNq20g5oglQiB1W4yrg==", V: "市立", M: "Municipal", RR: "しりつ", MM: "" },
    { id: "lrxUAHiZwIdHqp9JXGsxG+ur1HDn+g==", V: "シアトル市", M: "Seattle", RR: "しあとるし", MM: "" },
    { id: "8A7SPwxpjjcelF1dPLS7nUH/pBrrdg==", V: "広い", M: "Wide, Spacious", RR: "ひろい", MM: "" },
    { id: "W9Fu+hpQNYBPJeHjsmpBLnVAiF3CVQ==", V: "用いる", M: "To Utilize, To Use", RR: "もちいる", MM: "What do you need to utilize something? More cheese of course (もち)" },
    { id: "AdU0PLBTpglJom2Yn56ezRUb/yRC7g==", V: "公用", M: "Government (Official) Business", RR: "こうよう", MM: "Public task is a government business." },
    { id: "Pd3FwmasVcmhYUr+BWMwy7puQJxVTg==", V: "矢", M: "Arrow", RR: "や", MM: "" },
    { id: "0e5e/mU0NE5yClM6n1j7ZX9HEtymfw==", V: "人生", M: "One's Life, Human Life", RR: "じんせい", MM: "" },
    { id: "PbubMtXABQSBDd4t1WjaNt40K5oetQ==", V: "〜台", M: "Big Machine, Number of Machines", RR: "だい", MM: "" },
    { id: "xIcAhOzfNthxQQ2Tp5j9IhWnXixWwA==", V: "今日は", M: "Hello, Good Day", RR: "こんにちは", MM: "" },
    { id: "EtSBwfHtd1IUZljkK+GWUCDGa0kHeA==", V: "用", M: "Task, Business, Purpose, Function", RR: "よう", MM: "" },
    { id: "vt+QsQWcGasbWWZd7cHPAXYSR7oWfg==", V: "戸", M: "Japanese Style Door", RR: "と", MM: "" },
    { id: "Id6iTEhOw6mLIgR57HX+FC2esHemgg==", V: "号", M: "Number, Edition, Model", RR: "ごう", MM: "" },
    { id: "4kpSu82L58D4Oro4mhcSLhv1G5dcMA==", V: "中央", M: "Center, Central", RR: "ちゅうおう", MM: "" },
    { id: "jz6hUKY2USGS1BOW5TdZ8cHVmIuTzw==", V: "打つ", M: "To Hit, To Pound, To Type", RR: "うつ", MM: "After a kid gets hit, they'll use the word 'UF' (う) as an adjective" },
    { id: "GM0BzlwteXjSGo7xlsE3+ede/X/CNw==", V: "一打", M: "Strike, Stroke, Blow", RR: "いちだ", MM: "" },
    { id: "/ATD0gKoh3YLxUYSup2QbQiPOZQWUg==", V: "氷", M: "Ice", RR: "こおり", MM: "" },
    { id: "N+cYN+42wYF+zToVowASu81kDHRXzQ==", V: "かき氷", M: "Shaved Ice", RR: "かきごおり", MM: "" },
    { id: "EHbjdlkSQGavdeLgyyoFHjNAZXkQdg==", V: "申す", M: "To Say Humbly", RR: "もうす", MM: "" },
    { id: "ntUyP3r5b0qDWmqVLjEc1GHuYua2HQ==", V: "申し申し", M: "Hello (telephone)", RR: "もうしもうし - もしもし", MM: "" },
    { id: "zryLpqA47BDGkfk2LoColXahGxnqMA==", V: "子牛", M: "Calf, Baby Cow", RR: "こうし", MM: "" },
    { id: "9cNdVPYfqDgZFOs3Rxb3xBQ882wGYQ==", V: "切手", M: "Postage Stamp, Stamp", RR: "きって", MM: "Post kit - stamp (きって)" },
    { id: "qvCrqFKPbI/Uv6ghwoGl7cIMeGdHOQ==", V: "引き分け", M: "Tie, Draw", RR: "ひきわけ", MM: "Berabere. When you PULL something to SEPERATE them, you're making them even. Hence, Tie / Draw." },
    { id: "PKWpwqMWmmESMdN8rJ97qcPSzy9ugg==", V: "白い", M: "White", RR: "しろい", MM: "" },
    { id: "qSqvTHvUeVlcmVTAC4pGWZwJ3ys6dA==", V: "二十日", M: "Twentieth Day", RR: "はつか", MM: "Twenty hats for the twentieth day" },
    { id: "k7+5EqR7YUsTWeYsDkChpqHi5tkyvA==", V: "丸ごと", M: "In Its Entirety, Entirely, Wholly", RR: "まるごと", MM: "If you go to (ごと) a circle (まる), you need the ENTIRE circle." },
    { id: "e+ry3JzR5C0Kq9ZaheDVXM3ub6MTOQ==", V: "先ず", M: "First of all, To start with", RR: "まず", MM: "First of all, you need to go through the maze (まず)" },
    { id: "6pHlpQ87jmhUpICzMvc+6zCCiMeGkw==", V: "先", M: "Previous, Ahead, Past, Former", RR: "さき", MM: "I was previously a quite (sakin - さき) kid, but then I opened up." },
    { id: "t+buISwwBFFlWS3sbrYmOyGiq6wyRA==", V: "先々月", M: "Month before last", RR: "せんせんげつ", MM: "" },
    { id: "2Jp7jyKSaucC2qjTL0cEhtM/KX2cLQ==", V: "先月", M: "Last month", RR: "せんげつ", MM: "" },
    { id: "faDarTV1eieCtZY5/DuyKNInbPsD+w==", V: "先日", M: "The other day, A few days ago", RR: "せんじつ", MM: "The other day, fuJITSU (じつ) was popular." },
    { id: "/cEq7YFqfN41OBrnJDhgA7nqBqBC7Q==", V: "先生", M: "Teacher, Master, Doctor", RR: "せんせい", MM: "" },
    { id: "7vOWCEWEBTnttQFO8+WwUuCd9yUsmQ==", V: "出かける", M: "To go out", RR: "でかける", MM: "Going out, because there is a DEad (で) body here." },
    { id: "o/RkfBw4F44lS0PfeUAlWdw15ojQ9g==", V: "右手", M: "Right Hand", RR: "みぎて", MM: "" },
    { id: "4NMTgWNau7ZiCFnbET/vaqrhHIbUCg==", V: "四日", M: "Forth Day", RR: "よっか", MM: "" },
    { id: "VQyU3R0ITogXaCeIUUf8THpUJMNQkA==", V: "休み", M: "Rest, Break, Vacation, Holiday", RR: "やすみ", MM: "You'd say 'YASS!! if asked to go on a holiday." },
    { id: "zx6cVCLyrzm5Q4Uc3guUAQnXoqLDJA==", V: "休む", M: "To Rest", RR: "やすむ", MM: "" },
    { id: "JgVXy5cbNHalOlkGM9BUDTc64Pfvuw==", V: "休止", M: "Pause, Rest, Break", RR: "きゅうし", MM: "" },
    { id: "TogiE8kxkmadehrnSEq+KVtVONLjeA==", V: "休日", M: "Holiday", RR: "きゅうじつ", MM: "" },
    { id: "SC+KB7dd2NmrwN1dBYYq8JR20qfv6w==", V: "名人", M: "Master, Expert", RR: "めいじん", MM: "In Medellin (めいじん) there are MASTERS of entertainment." },
    { id: "6iQXsP/GvgDxE2escUGpG74lEcmlPA==", V: "名字", M: "Surname, Last Name, Family Name", RR: "みょうじ", MM: "MY (みょう) last name is..." },
    { id: "rQ3QVqJAgslof+0XxENJwCR0BHi+lA==", V: "字", M: "Character, Letter, Symbol", RR: "じ", MM: "" },
    { id: "DBzBLMds/FtvpuNnBEq/WrXJWrLGrQ==", V: "太字", M: "Bold Letter", RR: "ふとじ", MM: "" },
    { id: "8P/1ff+ASvmFY3Vi1wW6IWerq4DLdA==", V: "文字", M: "Letter (of the alphabet)", RR: "もじ", MM: "Think of eMOJI" },
    { id: "OUOy13pTSQmpMZ53fWyIR15D2BoSdw==", V: "一文字", M: "Straight Line", RR: "いちもんじ", MM: "In もじ reading of もう is shortened. This phrase is obviously longer so you use the longer version, もん." },
    { id: "0aAPwE0z8DbtGNJW8wgB0BI3IVLUiQ==", V: "２０１１年", M: "Year 2011", RR: "にせんじゅういちねん", MM: "" },
    { id: "XpbbYC8F/qL14R4HTWKTN/uqt2ECEg==", V: "年内", M: "Within a year, Within the year", RR: "ねんない", MM: "" },
    { id: "0OJ5jrBpSz+ac+SgQ3Wkf5p8vfT8iQ==", V: "年中", M: "Year Round, All Year, Whole Year, Throughout the year", RR: "ねんじゅう", MM: "" },
    { id: "gWft58GIDvWW5iEBba2saV5cOFTUPA==", V: "一年生", M: "First year student", RR: "いちねんせい", MM: "" },
    { id: "8seTdBV90i9Cx0T562tNXHBM6IIpaQ==", V: "少年", M: "Boy, Young Boy", RR: "しょうねん", MM: "" },
    { id: "blYgna8XOyzsRX6/IxwuQ1jW/uN2ng==", V: "去年", M: "Last Year", RR: "きょねん", MM: "" },
    { id: "HjoSyXEgwWbpdkMobwjp8c69V4031A==", V: "早い", M: "Early, Fast, Quick", RR: "はやい", MM: "HAYAmk (はや) it's too early" },
    { id: "/TJBTrfVzsddtdwz6q2SNPIt2CmWDQ==", V: "早々", M: "As soon as, Just after, Immediately after", RR: "そうそう, はやばや", MM: "If something is early twice, it's obviously important, you gotta do it ASAp" },
    { id: "5dhp9gkdgPQTyixVG6mMY4+qw4nHEQ==", V: "気", M: "Spirit, Energy", RR: "き", MM: "" },
    { id: "isXBC5ejnFoRrAhxmJUEsjJyKBmL3Q==", V: "気に入る", M: "To be pleased / happy / satisfied with", RR: "きないる", MM: "You enter into the energy, you'll be happy with it." },
    { id: "DhlVq99b8uMc85gz9HIMJ2UCX8PSmA==", V: "一気", M: "One breath, One go, One sitting", RR: "いっき", MM: "'One Energy' is weird. What gives you energy, breathing..." },
    { id: "g5fIIS+QVVEjg2COeX+V0EGOwBGu3g==", V: "気分", M: "Feeling, Mood", RR: "きぶん", MM: "PART of your SPIRIT is your mood." },
    { id: "thXlDdydr+PN6lOsm/BNcIboWVFLcg==", V: "人気", M: "Popular, Popularity", RR: "にんき", MM: "benimki populer degil ama seNINKI (にんき) populer." },
    { id: "bFgaGMwPVuX03Y6JvIMXlv3zaaejUg==", V: "元気", M: "Energy", RR: "げんき", MM: "" },
    { id: "ISkGa31Y05cppVIVGFcslJUq5Y65rg==", V: "天気", M: "Weather", RR: "てんき", MM: "Heaven energy determines the WEATHER because heaven is on top of us (不)" },
    { id: "VQvkSb+RPWiLiA5TGtAzExKmkS4c1g==", V: "本気", M: "Serious", RR: "ほんき", MM: "Books are serious matter. Book energy is therefor SERIOUS." },
    { id: "j0N8ZCAJPESsFW4XV0nv0UCz/DZ17g==", V: "平気", M: "Calm, All Right, Okay", RR: "へいき", MM: "When your energy is flat, you're calm." },
    { id: "TwTqDOdzOb4Gxsyejgr8AE1gT9c97g==", V: "一本気", M: "One Track Mind, Single mindedness", RR: "いっぽんぎ", MM: "(Sabit Fikirli)" },
    { id: "IaNch4ymRxF9esqFvOInbW9q1rcpMA==", V: "百万", M: "Million", RR: "ひゃくまん", MM: "" },
    { id: "MOnU8a1yt3yPsvxr+8Stw3MS8Ws8cg==", V: "四百", M: "Four Hundred", RR: "よんひゃく", MM: "" },
    { id: "7vaOB0h2hGbUsJjSrEZqtEECh0jofg==", V: "五百", M: "Five Hundred", RR: "ごひゃく", MM: "" },
    { id: "0KOZxBLyEpeNd6p1iNc62KD9RFUgYw==", V: "二百", M: "Two Hundred", RR: "にひゃく", MM: "" },
    { id: "e4il0OgwXo0DY3ClqevxTjomrRs/YQ==", V: "竹の子", M: "Bamboo Shoots", RR: "たけのこ", MM: "" },
    { id: "NYIvtffWsTjnuwRDysxA5izCAjv0Iw==", V: "竹", M: "Bamboo", RR: "たけ", MM: "" },
    { id: "nQVV+xvI+lgxs9hTtVj32+R+G6GpDQ==", V: "糸", M: "Thread", RR: "いと", MM: "" },
    { id: "lPR3SucH2rpTRF7ZW61EBuwXoawGrQ==", V: "耳", M: "Ear", RR: "みみ", MM: "" },
    { id: "eLlrU5I4JYQ8Z4SfkUFl4Yp1kTjT1A==", V: "虫", M: "Bug, Insect", RR: "むし", MM: "私は虫の女" },
    { id: "oUiYpHv0CO2GLtLEOwv4HmXiFJ+eCg==", V: "村", M: "Village, Rural Town", RR: "むら", MM: "" },
    { id: "w91gQhmhm3mPqYxQWsaKgEgnTIAj9g==", V: "村人", M: "Villager", RR: "むらびと", MM: "" },
    { id: "sspUlHsw/3t3vhC0od/+iXDMpFgbnw==", V: "男", M: "Man", RR: "おとこ", MM: "Men are into Cars (おと) from childhood (こ)" },
    { id: "m52KDx1kPNdKd/lXvvZVGRk7+G0hzw==", V: "町", M: "Town", RR: "まち", MM: "Towns have football teams, and host MATCHes (まち)." },
    { id: "z817TF2pVypU9Gmrf2TeTvoJkzN4eg==", V: "見る", M: "To see, To look", RR: "みる", MM: "" },
    { id: "oONEmS90STw0p4vzYiDl0Mu0ERsZ8A==", V: "見える", M: "Can see, visible", RR: "みえる", MM: "" },
    { id: "7l0cMIA+qCGqGi2gO7aEh2EsemKcfw==", V: "見せる", M: "To show", RR: "みせる", MM: "" },
    { id: "45JHFJ0SFfoTvwNVoR4B4XaR9hEuDQ==", V: "見分ける", M: "To distinguish, To tell apart", RR: "みわける", MM: "" },
    { id: "y2Evj0VCMC8xOpPOSB5+jhzVVgKqKA==", V: "花", M: "Flower", RR: "はな", MM: "" },
    { id: "xV4Tr0OJn00xnY/lAIG0AmKSjLkluw==", V: "花火", M: "Fireworks", RR: "はなび", MM: "" },
    { id: "bvqCn0qp+R1dPxMJbysoWM+f28mj3Q==", V: "花見", M: "Viewing cherry blossoms, sakura viewing", RR: "はなみ", MM: "" },
    { id: "J6iFQkcr01QH545zuAVDSuLnCsYtOw==", V: "見方", M: "Way of seeing, Point of view", RR: "みかた", MM: "If you don't share a point of view with people, they'll try to change yours with a SWORD (かた)な" },
    { id: "6tpdgllCSYtW3H0SDLOeyHYfI9rHjQ==", V: "月見", M: "Moon viewing", RR: "つきみ", MM: "" },
    { id: "1SFCVNIwsUTepde778gp6Z2Pz21IMw==", V: "貝", M: "Shell, Shellfish, Clam", RR: "かい", MM: "" },
    { id: "tdfh+uedqOTYiruSavEsOjTnINv0PQ==", V: "赤", M: "Red", RR: "あか", MM: "" },
    { id: "JQX/BI/yGGSceiGycyOC2qgviWRESg==", V: "赤ちゃん", M: "Baby", RR: "あかちゃん", MM: "" },
    { id: "AVyF6xDDetbrIm6K97gPeKeZ8rjodw==", V: "足りる", M: "To be enough, suffice", RR: "たりる", MM: "TAmam (た) yeterli." },
    { id: "MgzlA57XCmlEuJVrAnTQpyYhctFojA==", V: "足", M: "Foot, Leg", RR: "あし", MM: "What's in the foot? ASIl tendon (あし)" },
    { id: "", V: "", M: "", RR: "", MM: "" }
  ]
}
